import { Injectable } from '@angular/core';
import { ActivatedRoute, Router, NavigationEnd } from '@angular/router';
import { BehaviorSubject, filter, distinctUntilChanged } from 'rxjs';
import { Guid } from 'src/app/utils/guid';

export interface Breadcrumb {
  label?: string;
  alias?: string;
  skip?: boolean;
  skipAll?: boolean;
  info?: any;
  routeLink?: string;
  routeRegex?: string;
  isAutoGeneratedLabel?: boolean;
  loading?: boolean;
  navigable?: boolean;
}

@Injectable({ providedIn: 'root' })
export class BreadcrumbService {
  private baseHref = '/';

  /**
   * dynamicBreadcrumbStore holds information about dynamically updated breadcrumbs.
   * Breadcrumbs can be set from anywhere (component, service) in the app.
   * On every breadcrumb update check this store and use the info if available.
   */
  private dynamicBreadcrumbStore: Breadcrumb[] = [];

  /**
   * breadcrumbList for the current route
   * When breadcrumb info is changed dynamically, check if the currentBreadcrumbs is effected
   * If effected, update the change and emit a new stream
   */
  private currentBreadcrumbs: Breadcrumb[] = [];

  /**
   * Breadcrumbs observable to be subscribed by BreadcrumbComponent
   * Emits on every route change OR dynamic update of breadcrumb
   */
  private breadcrumbs = new BehaviorSubject<Breadcrumb[]>([]);
  public breadcrumbs$ = this.breadcrumbs.asObservable();

  private pathParamPrefix = ':';
  paramRegex = new RegExp(`\\${this.pathParamPrefix}\\b(\\w+)\\b`, 'g');

  constructor(private activatedRoute: ActivatedRoute, private router: Router) {
    this.detectRouteChanges();
  }

  setForAlias(alias: string, label: string) {
    if (!this.validateArguments(alias, label)) {
      return;
    }

    this.updateStore({ ...{ label }, alias });
  }

  /**
   * Whenever route changes build breadcrumb list again
   */
  private detectRouteChanges() {
    this.router.events
      .pipe(
        filter((event) => event instanceof NavigationEnd),
        distinctUntilChanged()
      )
      .subscribe((event) => {
        this.currentBreadcrumbs = [];
        this.prepareBreadcrumbList(this.activatedRoute.root, this.baseHref);
      });
  }

  private prepareBreadcrumbList(
    activatedRoute: ActivatedRoute,
    routeLinkPrefix: string
  ) {
    if (activatedRoute.routeConfig && activatedRoute.routeConfig.path) {
      const breadcrumbItem = this.prepareBreadcrumbItem(
        activatedRoute,
        routeLinkPrefix
      );
      this.currentBreadcrumbs.push(breadcrumbItem);

      if (activatedRoute.firstChild) {
        return this.prepareBreadcrumbList(
          activatedRoute.firstChild,
          breadcrumbItem.routeLink + '/'
        );
      }
    } else if (activatedRoute.firstChild) {
      return this.prepareBreadcrumbList(
        activatedRoute.firstChild,
        routeLinkPrefix
      );
    }

    const itemFromSkipedIndex = this.currentBreadcrumbs.findIndex(
      (i) => i.skipAll
    );
    if (itemFromSkipedIndex > -1) {
      this.currentBreadcrumbs.splice(itemFromSkipedIndex);
    }

    // remove breadcrumb items that needs to be hidden or don't have a label
    const breacrumbsToShow = this.currentBreadcrumbs.filter(
      (item) => !item.skip
    );

    this.breadcrumbs.next(breacrumbsToShow);
  }

  private prepareBreadcrumbItem(
    activatedRoute: ActivatedRoute,
    routeLinkPrefix: string
  ): Breadcrumb {
    const { path, breadcrumb } = this.parseRouteData(
      activatedRoute.routeConfig
    );

    // in case of path param get the resolved for param
    const resolvedPath = this.resolvePathParam(path, activatedRoute);
    const routeLink = `${routeLinkPrefix}${resolvedPath}`;

    // eslint-disable-next-line prefer-const
    let { label, alias, skip, info, skipAll, navigable } = this.getFromStore(
      breadcrumb.alias,
      routeLink
    );
    let isAutoGeneratedLabel = false;
    let loading = false;

    if (typeof label !== 'string') {
      if (typeof breadcrumb.label === 'string') {
        label = breadcrumb.label;
      } else {
        label = resolvedPath;
        loading = Guid.isGuid(label) || label.includes('/:');
        isAutoGeneratedLabel = true;
      }
    }

    return {
      label,
      alias: alias || breadcrumb.alias,
      skip: skip || breadcrumb.skip,
      info: info || breadcrumb.info,
      skipAll: skipAll || breadcrumb.skipAll,
      navigable: navigable || breadcrumb.navigable,
      routeLink,
      isAutoGeneratedLabel,
      loading,
    };
  }

  /**
   * For a specific route, breadcrumb can be defined either on parent data OR it's child(which has empty path) data
   * When both are defined, child takes precedence
   *
   * Ex: Below we are setting breadcrumb on both parent and child.
   * So, child takes precedence and "Defined On Child" is displayed for the route 'home'
   * { path: 'home', loadChildren: './home/home.module#HomeModule' , data: {breadcrumb: "Defined On Module"}}
   *                                                AND
   * children: [
   *   { path: '', component: ShowUserComponent, data: {breadcrumb: "Defined On Child" }
   * ]
   */
  private parseRouteData(routeConfig) {
    const { path, data = {} } = routeConfig;
    const breadcrumb = this.mergeWithBaseChildData(routeConfig, { ...data });

    return { path, breadcrumb };
  }

  private getFromStore(breadcrumbAlias: string, routeLink: string): Breadcrumb {
    let matchingItem;
    if (breadcrumbAlias) {
      matchingItem = this.dynamicBreadcrumbStore.find(
        (item) => item.alias === breadcrumbAlias
      );
    }

    if (!matchingItem && routeLink) {
      matchingItem = this.dynamicBreadcrumbStore.find((item) => {
        return (
          (item.routeLink && item.routeLink === routeLink) ||
          (item.routeRegex && new RegExp(item.routeRegex).test(routeLink + '/'))
        );
      });
    }

    return matchingItem || {};
  }

  /**
   * Update current breadcrumb definition and emit a new stream of breadcrumbs
   * Also update the store to reuse dynamic declarations
   */
  private updateStore(breadcrumb) {
    const { breadcrumbItemIndex, storeItemIndex } =
      this.getBreadcrumbIndexes(breadcrumb);

    // if breadcrumb is present in current breadcrumbs update it and emit new stream
    if (breadcrumbItemIndex > -1) {
      this.currentBreadcrumbs[breadcrumbItemIndex] = {
        ...this.currentBreadcrumbs[breadcrumbItemIndex],
        ...breadcrumb,
      };
      const breacrumbsToShow = this.currentBreadcrumbs.filter(
        (item) => !item.skip
      );

      this.currentBreadcrumbs[breadcrumbItemIndex].loading = false;
      this.breadcrumbs.next([...breacrumbsToShow]);
    }

    // If the store already has this route definition update it, else add
    if (storeItemIndex > -1) {
      this.dynamicBreadcrumbStore[storeItemIndex] = {
        ...this.dynamicBreadcrumbStore[storeItemIndex],
        ...breadcrumb,
      };
    } else {
      this.dynamicBreadcrumbStore.push(breadcrumb);
    }
  }

  private getBreadcrumbIndexes(breadcrumb): any {
    const { alias, routeLink, routeRegex } = breadcrumb;
    let indexMap = {};
    // identify macthing breadcrumb and store item
    if (alias) {
      indexMap = this.getBreadcrumbIndexesByType('alias', alias);
    } else if (routeLink) {
      indexMap = this.getBreadcrumbIndexesByType('routeLink', routeLink);
    } else if (routeRegex) {
      indexMap = this.getBreadcrumbIndexesByType('routeRegex', routeRegex);
    }
    return indexMap;
  }

  private getBreadcrumbIndexesByType(key: string, value: string) {
    const breadcrumbItemIndex = this.currentBreadcrumbs.findIndex(
      (item) => value === item[key]
    );
    const storeItemIndex = this.dynamicBreadcrumbStore.findIndex(
      (item) => value === item[key]
    );
    return { breadcrumbItemIndex, storeItemIndex };
  }

  private resolvePathParam(path: string, activatedRoute: ActivatedRoute) {
    // if the path segment is a route param, read the param value from url
    if (path.includes(this.pathParamPrefix)) {
      const matches = [...path.matchAll(this.paramRegex)].map(
        (match) => match[1]
      );
      matches.forEach((match) => {
        const param = activatedRoute.snapshot.params[match];
        path = path.replace(':' + match, param);
      });

      return path;
    }

    return path;
  }

  /**
   * get empty children of a module or Component. Empty child is the one with path: ''
   * When parent and it's children (that has empty route path) define data
   * merge them both with child taking precedence
   */
  private mergeWithBaseChildData(routeConfig, data): Breadcrumb {
    if (!routeConfig) {
      return this.getBreadcrumbOptions(data);
    }

    return this.getBreadcrumbOptions(data);
  }

  private validateArguments(alias: string, label: string) {
    if (alias === null || alias === undefined || typeof label !== 'string') {
      console.error(
        'Invalid first argument. Please pass a route path or a breadcrumb alias.'
      );
      return false;
    } else if (
      label === null ||
      label === undefined ||
      typeof label !== 'string'
    ) {
      console.error(
        'Invalid second argument. Please pass a string with the new value.'
      );
      return false;
    }
    return true;
  }

  /**
   * breadcrumb can be passed a label or an options object
   * If passed as a string convert to breadcrumb options object
   */
  private getBreadcrumbOptions(data) {
    let { breadcrumb } = data;
    if (typeof breadcrumb === 'string' || !breadcrumb) {
      breadcrumb = {
        label: breadcrumb,
      };
    }
    return breadcrumb;
  }
}
