CREATE VIEW[SEGURIDAD].[PERMISOS_HEREDADOS]
            AS
            select CAST(ROW_NUMBER() OVER(ORDER BY t1.IDPUESTO ASC) as int) AS ID
            , t1.IDPUESTO as IDPUESTO
            , t2.IDPERMISO as IDPERMISO
            , SEGURIDAD.OBTENER_ORIGEN_PUESTO_PERMISO(IDPUESTO, IDPERMISO) as ROLES
            from SEGURIDAD.ROL_PUESTO T1 
            INNER JOIN SEGURIDAD.ROL_PERMISO T2 ON T2.IDROL = T1.IDROL
            group by T1.IDPUESTO, T2.IDPERMISO
            
