CREATE TABLE [TAREA].[TAREA_ARCHIVO] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO1] INT NOT NULL,
    [ID_ELEMENTO2] INT NOT NULL,
    CONSTRAINT [PK_TAREA_ARCHIVO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TAREA_ARCHIVO_ID_ELEMENTO1] FOREIGN KEY ([ID_ELEMENTO1]) REFERENCES [TAREA].[TAREA] ([ID]),
    CONSTRAINT [FK_TAREA_ARCHIVO_ID_ELEMENTO2] FOREIGN KEY ([ID_ELEMENTO2]) REFERENCES [SISDOC].[ARCHIVO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ARCHIVO_ID_ELEMENTO2]
    ON [TAREA].[TAREA_ARCHIVO]([ID_ELEMENTO2] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ARCHIVO_ID_ELEMENTO1]
    ON [TAREA].[TAREA_ARCHIVO]([ID_ELEMENTO1] ASC);

