CREATE TABLE [TAREA].[TAREA_ACCION] (
    [ID]            INT            IDENTITY (1, 1) NOT NULL,
    [ID_TRANSICION] INT            NOT NULL,
    [ID_ACCION]     INT            NOT NULL,
    [PARAMETROS]    VARCHAR (2000) NULL,
    [DESCRIPCION]   VARCHAR (2000) NULL,
    [MOMENTO]       VARCHAR (1)    NOT NULL,
    [ORDEN]         INT            NOT NULL,
    [ACTIVO]        BIT            NOT NULL,
    CONSTRAINT [PK_TAREA_ACCION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TAREA_ACCION_ID_ACCION] FOREIGN KEY ([ID_ACCION]) REFERENCES [ENTORNO].[ACCION] ([ID]),
    CONSTRAINT [FK_TAREA_ACCION_ID_TRANSICION] FOREIGN KEY ([ID_TRANSICION]) REFERENCES [TAREA].[TAREA_TRANSICION] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ACCION_ID_TRANSICION]
    ON [TAREA].[TAREA_ACCION]([ID_TRANSICION] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ACCION_ID_ACCION]
    ON [TAREA].[TAREA_ACCION]([ID_ACCION] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ACCION_POR_ORDEN]
    ON [TAREA].[TAREA_ACCION]([ID_TRANSICION] ASC, [MOMENTO] ASC, [ORDEN] ASC);

