CREATE TABLE [TAREA].[TAREA] (
    [ID]             INT            IDENTITY (1, 1) NOT NULL,
    [CLASE_TAREA]    VARCHAR (15)   NOT NULL,
    [ID_PRESENTADOR] INT            NOT NULL,
    [ID_RESPONSABLE] INT            NULL,
    [CONTACTO]       VARCHAR (250)  NOT NULL,
    [TELEFONO]       VARCHAR (15)   NOT NULL,
    [EMAIL]          VARCHAR (50)   NOT NULL,
    [ID_ARCHIVADOR]  INT            NULL,
    [NOMBRE]         VARCHAR (250)  NOT NULL,
    [FECCRE]         DATETIME2 (7)  NOT NULL,
    [ID_CREADOR]     INT            NOT NULL,
    [FECMOD]         DATETIME2 (7)  NULL,
    [ID_MODIFICADOR] INT            NULL,
    [ID_CG]          INT            NOT NULL,
    [ID_TIPO]        INT            NOT NULL,
    [ID_ESTADO]      INT            NOT NULL,
    [DESCRIPCION]    VARCHAR (2000) NULL,
    [REFERENCIA]     VARCHAR (20)   NOT NULL,
    CONSTRAINT [PK_TAREA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TAREA_ID_ARCHIVADOR] FOREIGN KEY ([ID_ARCHIVADOR]) REFERENCES [SISDOC].[ARCHIVADOR] ([ID]),
    CONSTRAINT [FK_TAREA_ID_CG] FOREIGN KEY ([ID_CG]) REFERENCES [TERCEROS].[CENTRO_GESTOR] ([ID]),
    CONSTRAINT [FK_TAREA_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_TAREA_ID_ESTADO] FOREIGN KEY ([ID_ESTADO]) REFERENCES [TAREA].[TAREA_ESTADO] ([ID]),
    CONSTRAINT [FK_TAREA_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_TAREA_ID_PRESENTADOR] FOREIGN KEY ([ID_PRESENTADOR]) REFERENCES [TERCEROS].[INTERLOCUTOR] ([ID]),
    CONSTRAINT [FK_TAREA_ID_RESPONSABLE] FOREIGN KEY ([ID_RESPONSABLE]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_TAREA_ID_TIPO] FOREIGN KEY ([ID_TIPO]) REFERENCES [TAREA].[TAREA_TIPO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_REFERENCIA]
    ON [TAREA].[TAREA]([REFERENCIA] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_NOMBRE]
    ON [TAREA].[TAREA]([NOMBRE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ID_TIPO]
    ON [TAREA].[TAREA]([ID_TIPO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ID_RESPONSABLE]
    ON [TAREA].[TAREA]([ID_RESPONSABLE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ID_PRESENTADOR]
    ON [TAREA].[TAREA]([ID_PRESENTADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ID_MODIFICADOR]
    ON [TAREA].[TAREA]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ID_ESTADO]
    ON [TAREA].[TAREA]([ID_ESTADO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ID_CREADOR]
    ON [TAREA].[TAREA]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ID_CG]
    ON [TAREA].[TAREA]([ID_CG] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_ID_ARCHIVADOR]
    ON [TAREA].[TAREA]([ID_ARCHIVADOR] ASC) WHERE ([ID_ARCHIVADOR] IS NOT NULL);

