CREATE TABLE [TAREA].[TAREA_TIPO] (
    [ID]                 INT           IDENTITY (1, 1) NOT NULL,
    [ID_INTERVENTOR]     INT           NOT NULL,
    [CLASE_TAREA]        VARCHAR (15)  NOT NULL,
    [ID_TIPO_ARCHIVADOR] INT           NULL,
    [NOMBRE]             VARCHAR (250) NOT NULL,
    [ID_PADRE]           INT           NULL,
    [ID_GESTOR]          INT           NOT NULL,
    [ID_CONSULTOR]       INT           NOT NULL,
    [ID_ADM]             INT           NOT NULL,
    [ACTIVO]             BIT           NOT NULL,
    [TIPO_DTM]           VARCHAR (250) NOT NULL,
    [TIPO_DTO]           VARCHAR (250) NOT NULL,
    [CLASE_DE_LIBRO]     VARCHAR (20)  NOT NULL,
    [SIGLA]              VARCHAR (5)   NOT NULL,
    [ID_ESTADO]          INT           NOT NULL,
    CONSTRAINT [PK_TAREA_TIPO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TAREA_TIPO_ID_ADM] FOREIGN KEY ([ID_ADM]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_TAREA_TIPO_ID_CONSULTOR] FOREIGN KEY ([ID_CONSULTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_TAREA_TIPO_ID_ESTADO] FOREIGN KEY ([ID_ESTADO]) REFERENCES [TAREA].[TAREA_ESTADO] ([ID]),
    CONSTRAINT [FK_TAREA_TIPO_ID_GESTOR] FOREIGN KEY ([ID_GESTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_TAREA_TIPO_ID_INTERVENTOR] FOREIGN KEY ([ID_INTERVENTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_TAREA_TIPO_ID_PADRE] FOREIGN KEY ([ID_PADRE]) REFERENCES [TAREA].[TAREA_TIPO] ([ID]),
    CONSTRAINT [FK_TAREA_TIPO_ID_TIPO_ARCHIVADOR] FOREIGN KEY ([ID_TIPO_ARCHIVADOR]) REFERENCES [SISDOC].[ARCHIVADOR_TIPO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_TIPO_NOMBRE]
    ON [TAREA].[TAREA_TIPO]([NOMBRE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_TIPO_ID_TIPO_ARCHIVADOR]
    ON [TAREA].[TAREA_TIPO]([ID_TIPO_ARCHIVADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_TIPO_ID_PADRE]
    ON [TAREA].[TAREA_TIPO]([ID_PADRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_TIPO_ID_INTERVENTOR]
    ON [TAREA].[TAREA_TIPO]([ID_INTERVENTOR] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_TIPO_ID_GESTOR]
    ON [TAREA].[TAREA_TIPO]([ID_GESTOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_TIPO_ID_ESTADO]
    ON [TAREA].[TAREA_TIPO]([ID_ESTADO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_TIPO_ID_CONSULTOR]
    ON [TAREA].[TAREA_TIPO]([ID_CONSULTOR] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_TIPO_ID_ADM]
    ON [TAREA].[TAREA_TIPO]([ID_ADM] ASC);

