CREATE TABLE [TAREA].[TAREA_TRAZA] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [NOMBRE]      VARCHAR (250)  NOT NULL,
    [ID_ELEMENTO] INT            NOT NULL,
    [DESCRIPCION] VARCHAR (2000) NULL,
    [ID_CREADOR]  INT            NOT NULL,
    [CREADO_EL]   DATETIME2 (7)  NOT NULL,
    [CREADOR]     AS             ([ENTORNO].[CC_USUARIO_EXPRESION]([ID_CREADOR])),
    CONSTRAINT [PK_TAREA_TRAZA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TAREA_TRAZA_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_TAREA_TRAZA_ID_ELEMENTO] FOREIGN KEY ([ID_ELEMENTO]) REFERENCES [TAREA].[TAREA] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_TRAZA_ID_ELEMENTO]
    ON [TAREA].[TAREA_TRAZA]([ID_ELEMENTO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_TRAZA_ID_CREADOR]
    ON [TAREA].[TAREA_TRAZA]([ID_CREADOR] ASC);

