CREATE TABLE [TAREA].[TAREA_TRANSICION] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]          VARCHAR (250) NOT NULL,
    [ID_ORIGEN]       INT           NOT NULL,
    [ID_DESTINO]      INT           NOT NULL,
    [DEL_SISTEMA]     BIT           NOT NULL,
    [CON_OBSERVACION] BIT           NOT NULL,
    [ASUNTO]          VARCHAR (250) NULL,
    [ID_PERMISO]      INT           NOT NULL,
    [ACTIVO]          BIT           NOT NULL,
    CONSTRAINT [PK_TAREA_TRANSICION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TAREA_TRANSICION_ID_DESTINO] FOREIGN KEY ([ID_DESTINO]) REFERENCES [TAREA].[TAREA_ESTADO] ([ID]),
    CONSTRAINT [FK_TAREA_TRANSICION_ID_ORIGEN] FOREIGN KEY ([ID_ORIGEN]) REFERENCES [TAREA].[TAREA_ESTADO] ([ID]),
    CONSTRAINT [FK_TAREA_TRANSICION_ID_PERMISO] FOREIGN KEY ([ID_PERMISO]) REFERENCES [SEGURIDAD].[PERMISO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_TRANSICION_NOMBRE]
    ON [TAREA].[TAREA_TRANSICION]([NOMBRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_TRANSICION_ID_PERMISO]
    ON [TAREA].[TAREA_TRANSICION]([ID_PERMISO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_TRANSICION_ID_ORIGEN]
    ON [TAREA].[TAREA_TRANSICION]([ID_ORIGEN] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_TRANSICION_ID_DESTINO]
    ON [TAREA].[TAREA_TRANSICION]([ID_DESTINO] ASC);

