CREATE TABLE [TAREA].[TAREA_ESTADO] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]     VARCHAR (250) NOT NULL,
    [ID_PERMISO] INT           NOT NULL,
    [INICIAL]    BIT           NOT NULL,
    [TERMINADO]  BIT           NOT NULL,
    [CANCELADO]  BIT           NOT NULL,
    [ORDEN]      INT           NOT NULL,
    CONSTRAINT [PK_TAREA_ESTADO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TAREA_ESTADO_ID_PERMISO] FOREIGN KEY ([ID_PERMISO]) REFERENCES [SEGURIDAD].[PERMISO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_ESTADO_NOMBRE]
    ON [TAREA].[TAREA_ESTADO]([NOMBRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TAREA_ESTADO_ID_PERMISO]
    ON [TAREA].[TAREA_ESTADO]([ID_PERMISO] ASC);

