CREATE TABLE [TAREA].[TAREA_ARCHIVADOR] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO1] INT NOT NULL,
    [ID_ELEMENTO2] INT NOT NULL,
    CONSTRAINT [PK_TAREA_ARCHIVADOR] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TAREA_ARCHIVADOR_ID_ELEMENTO1] FOREIGN KEY ([ID_ELEMENTO1]) REFERENCES [TAREA].[TAREA] ([ID]),
    CONSTRAINT [FK_TAREA_ARCHIVADOR_ID_ELEMENTO2] FOREIGN KEY ([ID_ELEMENTO2]) REFERENCES [SISDOC].[ARCHIVADOR] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ARCHIVADOR_ID_ELEMENTO2]
    ON [TAREA].[TAREA_ARCHIVADOR]([ID_ELEMENTO2] ASC);


GO
CREATE NONCLUSTERED INDEX [I_TAREA_ARCHIVADOR_ID_ELEMENTO1]
    ON [TAREA].[TAREA_ARCHIVADOR]([ID_ELEMENTO1] ASC);

