CREATE TABLE [TRABAJO].[CORREO] (
    [ID]         INT            IDENTITY (1, 1) NOT NULL,
    [EMISOR]     VARCHAR (250)  NOT NULL,
    [RECEPTORES] VARCHAR (2000) NOT NULL,
    [ASUNTO]     VARCHAR (500)  NOT NULL,
    [CUERPO]     VARCHAR (MAX)  NOT NULL,
    [ELEMENTOS]  VARCHAR (2000) NULL,
    [ARCHIVOS]   VARCHAR (MAX)  NULL,
    [ID_USUARIO] INT            NOT NULL,
    [CREADO]     DATETIME2 (7)  NOT NULL,
    [ENVIADO]    DATETIME2 (7)  NOT NULL,
    CONSTRAINT [PK_CORREO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TRABAJO_DE_USUARIO_ID_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [ENTORNO].[USUARIO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_CORREO_ID_USUARIO]
    ON [TRABAJO].[CORREO]([ID_USUARIO] ASC);

