CREATE TABLE [TRABAJO].[ERROR] (
    [ID]                 INT            IDENTITY (1, 1) NOT NULL,
    [ID_TRABAJO_USUARIO] INT            NOT NULL,
    [ERROR]              VARCHAR (2000) NOT NULL,
    [DETALLE]            VARCHAR (MAX)  NULL,
    [FECHA]              DATETIME2 (7)  NOT NULL,
    CONSTRAINT [PK_ERROR] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ERROR_DE_TRABAJO_ID_TRABAJO_USUARIO] FOREIGN KEY ([ID_TRABAJO_USUARIO]) REFERENCES [TRABAJO].[USUARIO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_ERROR_ID_TRABAJO_USUARIO]
    ON [TRABAJO].[ERROR]([ID_TRABAJO_USUARIO] ASC);

