CREATE TABLE [TRABAJO].[SEMAFORO] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [ID_TRABAJO] INT           NOT NULL,
    [INICIADO]   DATETIME2 (7) NOT NULL,
    [LOGIN]      VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_SEMAFORO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AK_SEMAFORO_ID_TRABAJO] UNIQUE NONCLUSTERED ([ID_TRABAJO] ASC)
);

