CREATE TABLE [TRABAJO].[TRABAJO] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [ES_DLL]          BIT           NOT NULL,
    [DLL]             VARCHAR (250) NULL,
    [CLASE]           VARCHAR (250) NULL,
    [METODO]          VARCHAR (250) NULL,
    [ESQUEMA]         VARCHAR (250) NULL,
    [PA]              VARCHAR (250) NULL,
    [COMUNICAR_FIN]   BIT           NOT NULL,
    [COMUNICAR_ERROR] BIT           NOT NULL,
    [ID_EJECUTOR]     INT           NULL,
    [ID_INFORMAR_A]   INT           NULL,
    [NOMBRE]          VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_TRABAJO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TRABAJO_ID_EJECUTOR] FOREIGN KEY ([ID_EJECUTOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_TRABAJO_ID_INFORMAR_A] FOREIGN KEY ([ID_INFORMAR_A]) REFERENCES [SEGURIDAD].[PUESTO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_TRABAJO_ID_EJECUTOR]
    ON [TRABAJO].[TRABAJO]([ID_EJECUTOR] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_TRABAJO_ID_INFORMAR_A]
    ON [TRABAJO].[TRABAJO]([ID_INFORMAR_A] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_TRABAJO_METODO]
    ON [TRABAJO].[TRABAJO]([NOMBRE] ASC, [DLL] ASC, [CLASE] ASC, [METODO] ASC) WHERE ([DLL] IS NOT NULL AND [CLASE] IS NOT NULL AND [METODO] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [I_TRABAJO_NOMBRE]
    ON [TRABAJO].[TRABAJO]([NOMBRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_TRABAJO_PA]
    ON [TRABAJO].[TRABAJO]([NOMBRE] ASC, [ESQUEMA] ASC, [PA] ASC) WHERE ([ESQUEMA] IS NOT NULL AND [PA] IS NOT NULL);

