CREATE TABLE [TRABAJO].[TRAZA] (
    [ID]                 INT           IDENTITY (1, 1) NOT NULL,
    [ID_TRABAJO_USUARIO] INT           NOT NULL,
    [LOG]                VARCHAR (MAX) NOT NULL,
    [FECHA]              DATETIME2 (7) NOT NULL,
    CONSTRAINT [PK_TRAZA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_LOG_DE_TRABAJO_ID_TRABAJO_USUARIO] FOREIGN KEY ([ID_TRABAJO_USUARIO]) REFERENCES [TRABAJO].[USUARIO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_TRAZA_ID_TRABAJO_USUARIO]
    ON [TRABAJO].[TRAZA]([ID_TRABAJO_USUARIO] ASC);

