CREATE TABLE [TRABAJO].[USUARIO] (
    [ID]           INT            IDENTITY (1, 1) NOT NULL,
    [ID_TRABAJO]   INT            NOT NULL,
    [ID_EJECUTOR]  INT            NOT NULL,
    [ID_SOMETEDOR] INT            NOT NULL,
    [ENTRADA]      DATETIME2 (7)  NOT NULL,
    [PLANIFICADO]  DATETIME2 (7)  NOT NULL,
    [INICIADO]     DATETIME2 (7)  NULL,
    [TERMINADO]    DATETIME2 (7)  NULL,
    [ESTADO]       CHAR (2)       NOT NULL,
    [PERIODICIDAD] INT            NOT NULL,
    [PARAMETROS]   VARCHAR (2000) NULL,
    CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TRABAJO_DE_USUARIO_ID_EJECUTOR] FOREIGN KEY ([ID_EJECUTOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_TRABAJO_DE_USUARIO_ID_SOMETEDOR] FOREIGN KEY ([ID_SOMETEDOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_TRABAJO_DE_USUARIO_ID_TRABAJO] FOREIGN KEY ([ID_TRABAJO]) REFERENCES [TRABAJO].[TRABAJO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_USUARIO_ID_EJECUTOR]
    ON [TRABAJO].[USUARIO]([ID_EJECUTOR] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_USUARIO_ID_SOMETEDOR]
    ON [TRABAJO].[USUARIO]([ID_SOMETEDOR] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_USUARIO_ID_TRABAJO]
    ON [TRABAJO].[USUARIO]([ID_TRABAJO] ASC);

