CREATE TABLE [REGISTRO].[REGISTRO_ESTADO] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]     VARCHAR (250) NOT NULL,
    [ID_PERMISO] INT           NOT NULL,
    [INICIAL]    BIT           NOT NULL,
    [TERMINADO]  BIT           NOT NULL,
    [CANCELADO]  BIT           NOT NULL,
    [ORDEN]      INT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_REGISTRO_ESTADO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_ESTADO_ID_PERMISO] FOREIGN KEY ([ID_PERMISO]) REFERENCES [SEGURIDAD].[PERMISO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_ESTADO_ID_PERMISO]
    ON [REGISTRO].[REGISTRO_ESTADO]([ID_PERMISO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_ESTADO_NOMBRE]
    ON [REGISTRO].[REGISTRO_ESTADO]([NOMBRE] ASC);

