CREATE TABLE [REGISTRO].[REGISTRO_ARCHIVADOR] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO1] INT NOT NULL,
    [ID_ELEMENTO2] INT NOT NULL,
    CONSTRAINT [PK_REGISTRO_ARCHIVADOR] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_ARCHIVADOR_ID_ELEMENTO1] FOREIGN KEY ([ID_ELEMENTO1]) REFERENCES [REGISTRO].[REGISTRO] ([ID]),
    CONSTRAINT [FK_REGISTRO_ARCHIVADOR_ID_ELEMENTO2] FOREIGN KEY ([ID_ELEMENTO2]) REFERENCES [SISDOC].[ARCHIVADOR] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ARCHIVADOR_ID_ELEMENTO1]
    ON [REGISTRO].[REGISTRO_ARCHIVADOR]([ID_ELEMENTO1] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ARCHIVADOR_ID_ELEMENTO2]
    ON [REGISTRO].[REGISTRO_ARCHIVADOR]([ID_ELEMENTO2] ASC);

