CREATE TABLE [REGISTRO].[REGISTRO_INTERLOCUTOR] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO1] INT NOT NULL,
    [ID_ELEMENTO2] INT NOT NULL,
    CONSTRAINT [PK_REGISTRO_INTERLOCUTOR] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_INTERLOCUTOR_ID_ELEMENTO1] FOREIGN KEY ([ID_ELEMENTO1]) REFERENCES [REGISTRO].[REGISTRO] ([ID]),
    CONSTRAINT [FK_REGISTRO_INTERLOCUTOR_ID_ELEMENTO2] FOREIGN KEY ([ID_ELEMENTO2]) REFERENCES [TERCEROS].[INTERLOCUTOR] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_INTERLOCUTOR_ID_ELEMENTO2]
    ON [REGISTRO].[REGISTRO_INTERLOCUTOR]([ID_ELEMENTO2] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_INTERLOCUTOR_ID_ELEMENTO1]
    ON [REGISTRO].[REGISTRO_INTERLOCUTOR]([ID_ELEMENTO1] ASC);

