CREATE TABLE [REGISTRO].[REGISTRO_HISTORIA] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO]    INT           NOT NULL,
    [FECHA]          DATETIME2 (7) NOT NULL,
    [ID_USUARIO]     INT           NOT NULL,
    [ID_ESTADO]      INT           NOT NULL,
    [TIEMPO]         BIGINT        NULL,
    [ID_TRANSICION]  INT           NULL,
    [ID_OBSERVACION] INT           NULL,
    CONSTRAINT [PK_REGISTRO_HISTORIA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_HISTORIA_ID_ELEMENTO] FOREIGN KEY ([ID_ELEMENTO]) REFERENCES [REGISTRO].[REGISTRO] ([ID]),
    CONSTRAINT [FK_REGISTRO_HISTORIA_ID_ESTADO] FOREIGN KEY ([ID_ESTADO]) REFERENCES [REGISTRO].[REGISTRO_ESTADO] ([ID]),
    CONSTRAINT [FK_REGISTRO_HISTORIA_ID_OBSERVACION] FOREIGN KEY ([ID_OBSERVACION]) REFERENCES [REGISTRO].[REGISTRO_OBSERVACION] ([ID]),
    CONSTRAINT [FK_REGISTRO_HISTORIA_ID_TRANSICION] FOREIGN KEY ([ID_TRANSICION]) REFERENCES [REGISTRO].[REGISTRO_TRANSICION] ([ID]),
    CONSTRAINT [FK_REGISTRO_HISTORIA_ID_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [ENTORNO].[USUARIO] ([ID])
);




GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_HISTORIA_ID_ELEMENTO]
    ON [REGISTRO].[REGISTRO_HISTORIA]([ID_ELEMENTO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_HISTORIA_ID_ESTADO]
    ON [REGISTRO].[REGISTRO_HISTORIA]([ID_ESTADO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_HISTORIA_ID_OBSERVACION]
    ON [REGISTRO].[REGISTRO_HISTORIA]([ID_OBSERVACION] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_HISTORIA_ID_TRANSICION]
    ON [REGISTRO].[REGISTRO_HISTORIA]([ID_TRANSICION] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_HISTORIA_ID_USUARIO]
    ON [REGISTRO].[REGISTRO_HISTORIA]([ID_USUARIO] ASC);

