CREATE TABLE [REGISTRO].[REGISTRO_OBSERVACION] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [NOMBRE]      VARCHAR (250)  NOT NULL,
    [ID_ELEMENTO] INT            NOT NULL,
    [DESCRIPCION] VARCHAR (2000) NULL,
    [ID_CREADOR]  INT            NOT NULL,
    [CREADO_EL]   DATETIME2 (7)  NOT NULL,
    [CREADOR]     AS             ([ENTORNO].[CC_USUARIO_EXPRESION]([ID_CREADOR])),
    [ELEMENTO]    AS             ([REGISTRO].[CC_REGISTRO_NOMBRE]([ID_ELEMENTO])),
    CONSTRAINT [PK_REGISTRO_OBSERVACION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_OBSERVACION_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_REGISTRO_OBSERVACION_ID_ELEMENTO] FOREIGN KEY ([ID_ELEMENTO]) REFERENCES [REGISTRO].[REGISTRO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_OBSERVACION_ID_CREADOR]
    ON [REGISTRO].[REGISTRO_OBSERVACION]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_OBSERVACION_ID_ELEMENTO]
    ON [REGISTRO].[REGISTRO_OBSERVACION]([ID_ELEMENTO] ASC);

