CREATE TABLE [REGISTRO].[REGISTRO_ACCION] (
    [ID]            INT            IDENTITY (1, 1) NOT NULL,
    [ID_TRANSICION] INT            NOT NULL,
    [ID_ACCION]     INT            NOT NULL,
    [PARAMETROS]    VARCHAR (2000) NULL,
    [DESCRIPCION]   VARCHAR (2000) NULL,
    [MOMENTO]       VARCHAR (1)    NOT NULL,
    [ORDEN]         INT            DEFAULT ((0)) NOT NULL,
    [ACTIVO]        BIT            DEFAULT (CONVERT([bit],(0))) NOT NULL,
    CONSTRAINT [PK_REGISTRO_ACCION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_ACCION_ID_ACCION] FOREIGN KEY ([ID_ACCION]) REFERENCES [ENTORNO].[ACCION] ([ID]),
    CONSTRAINT [FK_REGISTRO_ACCION_ID_TRANSICION] FOREIGN KEY ([ID_TRANSICION]) REFERENCES [REGISTRO].[REGISTRO_TRANSICION] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ACCION_ID_ACCION]
    ON [REGISTRO].[REGISTRO_ACCION]([ID_ACCION] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ACCION_ID_TRANSICION]
    ON [REGISTRO].[REGISTRO_ACCION]([ID_TRANSICION] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ACCION_POR_ORDEN]
    ON [REGISTRO].[REGISTRO_ACCION]([ID_TRANSICION] ASC, [MOMENTO] ASC, [ORDEN] ASC);

