CREATE TABLE [REGISTRO].[REGISTRO_TRANSICION] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]          VARCHAR (250) NOT NULL,
    [ID_ORIGEN]       INT           NOT NULL,
    [ID_DESTINO]      INT           NOT NULL,
    [DEL_SISTEMA]     BIT           NOT NULL,
    [CON_OBSERVACION] BIT           NOT NULL,
    [ASUNTO]          VARCHAR (250) NULL,
    [ID_PERMISO]      INT           NOT NULL,
    [ACTIVO]          BIT           DEFAULT (CONVERT([bit],(0))) NOT NULL,
    CONSTRAINT [PK_REGISTRO_TRANSICION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_TRANSICION_ID_DESTINO] FOREIGN KEY ([ID_DESTINO]) REFERENCES [REGISTRO].[REGISTRO_ESTADO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TRANSICION_ID_ORIGEN] FOREIGN KEY ([ID_ORIGEN]) REFERENCES [REGISTRO].[REGISTRO_ESTADO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TRANSICION_ID_PERMISO] FOREIGN KEY ([ID_PERMISO]) REFERENCES [SEGURIDAD].[PERMISO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_TRANSICION_ID_DESTINO]
    ON [REGISTRO].[REGISTRO_TRANSICION]([ID_DESTINO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_TRANSICION_ID_ORIGEN]
    ON [REGISTRO].[REGISTRO_TRANSICION]([ID_ORIGEN] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_TRANSICION_ID_PERMISO]
    ON [REGISTRO].[REGISTRO_TRANSICION]([ID_PERMISO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_TRANSICION_NOMBRE]
    ON [REGISTRO].[REGISTRO_TRANSICION]([NOMBRE] ASC);

