CREATE TABLE [REGISTRO].[REGISTRO] (
    [ID]                    INT            IDENTITY (1, 1) NOT NULL,
    [ID_CG]                 INT            NOT NULL,
    [ID_TIPO]               INT            NOT NULL,
    [ID_ESTADO]             INT            NOT NULL,
    [CLASE_ES]              VARCHAR (1)    NOT NULL,
    [DESCRIPCION]           VARCHAR (2000) NULL,
    [REFERENCIA]            VARCHAR (20)   NOT NULL,
    [ID_PRESENTADOR]        INT            NOT NULL,
    [ID_ARCHIVADOR_ENTRADA] INT            NULL,
    [ID_ARCHIVADOR_SALIDA]  INT            NULL,
    [ID_ARCHIVADOR_INTERNO] INT            NULL,
    [NOMBRE]                VARCHAR (250)  NOT NULL,
    [FECCRE]                DATETIME2 (7)  NOT NULL,
    [ID_CREADOR]            INT            NOT NULL,
    [FECMOD]                DATETIME2 (7)  NULL,
    [ID_MODIFICADOR]        INT            NULL,
    [CONTACTO]              VARCHAR (250)  NOT NULL,
    [EMAIL]                 VARCHAR (50)   NOT NULL,
    [TELEFONO]              VARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_REGISTRO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_ID_ARCHIVADOR_ENTRADA] FOREIGN KEY ([ID_ARCHIVADOR_ENTRADA]) REFERENCES [SISDOC].[ARCHIVADOR] ([ID]),
    CONSTRAINT [FK_REGISTRO_ID_ARCHIVADOR_INTERNO] FOREIGN KEY ([ID_ARCHIVADOR_INTERNO]) REFERENCES [SISDOC].[ARCHIVADOR] ([ID]),
    CONSTRAINT [FK_REGISTRO_ID_ARCHIVADOR_SALIDA] FOREIGN KEY ([ID_ARCHIVADOR_SALIDA]) REFERENCES [SISDOC].[ARCHIVADOR] ([ID]),
    CONSTRAINT [FK_REGISTRO_ID_CG] FOREIGN KEY ([ID_CG]) REFERENCES [TERCEROS].[CENTRO_GESTOR] ([ID]),
    CONSTRAINT [FK_REGISTRO_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_REGISTRO_ID_ESTADO] FOREIGN KEY ([ID_ESTADO]) REFERENCES [REGISTRO].[REGISTRO_ESTADO] ([ID]),
    CONSTRAINT [FK_REGISTRO_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_REGISTRO_ID_PRESENTADOR] FOREIGN KEY ([ID_PRESENTADOR]) REFERENCES [TERCEROS].[INTERLOCUTOR] ([ID]),
    CONSTRAINT [FK_REGISTRO_ID_TIPO] FOREIGN KEY ([ID_TIPO]) REFERENCES [REGISTRO].[REGISTRO_TIPO] ([ID])
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_ID_ARCHIVADOR_ENTRADA]
    ON [REGISTRO].[REGISTRO]([ID_ARCHIVADOR_ENTRADA] ASC) WHERE ([ID_ARCHIVADOR_ENTRADA] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_ID_ARCHIVADOR_INTERNO]
    ON [REGISTRO].[REGISTRO]([ID_ARCHIVADOR_INTERNO] ASC) WHERE ([ID_ARCHIVADOR_INTERNO] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_ID_ARCHIVADOR_SALIDA]
    ON [REGISTRO].[REGISTRO]([ID_ARCHIVADOR_SALIDA] ASC) WHERE ([ID_ARCHIVADOR_SALIDA] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ID_CG]
    ON [REGISTRO].[REGISTRO]([ID_CG] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ID_CREADOR]
    ON [REGISTRO].[REGISTRO]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ID_ESTADO]
    ON [REGISTRO].[REGISTRO]([ID_ESTADO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ID_MODIFICADOR]
    ON [REGISTRO].[REGISTRO]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ID_PRESENTADOR]
    ON [REGISTRO].[REGISTRO]([ID_PRESENTADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_ID_TIPO]
    ON [REGISTRO].[REGISTRO]([ID_TIPO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_NOMBRE]
    ON [REGISTRO].[REGISTRO]([NOMBRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_REFERENCIA]
    ON [REGISTRO].[REGISTRO]([REFERENCIA] ASC);

