CREATE TABLE [REGISTRO].[REGISTRO_PERMISO] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO]  INT NOT NULL,
    [ID_GESTOR]    INT NOT NULL,
    [ID_CONSULTOR] INT NOT NULL,
    [ID_ADM]       INT NOT NULL,
    CONSTRAINT [PK_REGISTRO_PERMISO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_PERMISO_ID_ADM] FOREIGN KEY ([ID_ADM]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_REGISTRO_PERMISO_ID_CONSULTOR] FOREIGN KEY ([ID_CONSULTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_REGISTRO_PERMISO_ID_ELEMENTO] FOREIGN KEY ([ID_ELEMENTO]) REFERENCES [REGISTRO].[REGISTRO] ([ID]),
    CONSTRAINT [FK_REGISTRO_PERMISO_ID_GESTOR] FOREIGN KEY ([ID_GESTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_PERMISO_ID_ADM]
    ON [REGISTRO].[REGISTRO_PERMISO]([ID_ADM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_PERMISO_ID_CONSULTOR]
    ON [REGISTRO].[REGISTRO_PERMISO]([ID_CONSULTOR] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_PERMISO_ID_ELEMENTO]
    ON [REGISTRO].[REGISTRO_PERMISO]([ID_ELEMENTO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_PERMISO_ID_GESTOR]
    ON [REGISTRO].[REGISTRO_PERMISO]([ID_GESTOR] ASC);

