CREATE TABLE [REGISTRO].[REGISTRO_TIPO] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [ID_ESTADO]       INT           NOT NULL,
    [ID_INTERVENTOR]  INT           NOT NULL,
    [CLASE_ES]        VARCHAR (1)   NOT NULL,
    [ID_TIPO_ENTRADA] INT           NULL,
    [ID_TIPO_SALIDA]  INT           NULL,
    [ID_TIPO_INTERNO] INT           NULL,
    [NOMBRE]          VARCHAR (250) NOT NULL,
    [ID_PADRE]        INT           NULL,
    [ID_GESTOR]       INT           NOT NULL,
    [ID_CONSULTOR]    INT           NOT NULL,
    [ID_ADM]          INT           NOT NULL,
    [ACTIVO]          BIT           NOT NULL,
    [TIPO_DTM]        VARCHAR (250) NOT NULL,
    [TIPO_DTO]        VARCHAR (250) NOT NULL,
    [CLASE_DE_LIBRO]  VARCHAR (20)  NOT NULL,
    [SIGLA]           VARCHAR (5)   DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_REGISTRO_TIPO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_REGISTRO_TIPO_ID_ADM] FOREIGN KEY ([ID_ADM]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TIPO_ID_CONSULTOR] FOREIGN KEY ([ID_CONSULTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TIPO_ID_ESTADO] FOREIGN KEY ([ID_ESTADO]) REFERENCES [REGISTRO].[REGISTRO_ESTADO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TIPO_ID_GESTOR] FOREIGN KEY ([ID_GESTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TIPO_ID_INTERVENTOR] FOREIGN KEY ([ID_INTERVENTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TIPO_ID_PADRE] FOREIGN KEY ([ID_PADRE]) REFERENCES [REGISTRO].[REGISTRO_TIPO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TIPO_ID_TIPO_ENTRADA] FOREIGN KEY ([ID_TIPO_ENTRADA]) REFERENCES [SISDOC].[ARCHIVADOR_TIPO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TIPO_ID_TIPO_INTERNO] FOREIGN KEY ([ID_TIPO_INTERNO]) REFERENCES [SISDOC].[ARCHIVADOR_TIPO] ([ID]),
    CONSTRAINT [FK_REGISTRO_TIPO_ID_TIPO_SALIDA] FOREIGN KEY ([ID_TIPO_SALIDA]) REFERENCES [SISDOC].[ARCHIVADOR_TIPO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_TIPO_ID_ADM]
    ON [REGISTRO].[REGISTRO_TIPO]([ID_ADM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_TIPO_ID_CONSULTOR]
    ON [REGISTRO].[REGISTRO_TIPO]([ID_CONSULTOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_TIPO_ID_ESTADO]
    ON [REGISTRO].[REGISTRO_TIPO]([ID_ESTADO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_TIPO_ID_GESTOR]
    ON [REGISTRO].[REGISTRO_TIPO]([ID_GESTOR] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_TIPO_ID_INTERVENTOR]
    ON [REGISTRO].[REGISTRO_TIPO]([ID_INTERVENTOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_TIPO_ID_PADRE]
    ON [REGISTRO].[REGISTRO_TIPO]([ID_PADRE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_TIPO_ID_TIPO_ENTRADA]
    ON [REGISTRO].[REGISTRO_TIPO]([ID_TIPO_ENTRADA] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_TIPO_ID_TIPO_INTERNO]
    ON [REGISTRO].[REGISTRO_TIPO]([ID_TIPO_INTERNO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_REGISTRO_TIPO_ID_TIPO_SALIDA]
    ON [REGISTRO].[REGISTRO_TIPO]([ID_TIPO_SALIDA] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_REGISTRO_TIPO_NOMBRE]
    ON [REGISTRO].[REGISTRO_TIPO]([NOMBRE] ASC);

