


ALTER DATABASE SE_SECIFY SET OFFLINE;


ALTER DATABASE SE_SECIFY SET ONLINE;


SELECT file_id, name AS [logical_file_name], physical_name
FROM sys.database_files;

ALTER DATABASE SE_SECIFY MODIFY FILE (NAME = 'SE_FEMDEK', NEWNAME = 'SE_SECIFY');
ALTER DATABASE SE_SECIFY MODIFY FILE (NAME = 'SE_FEMDEK_log', NEWNAME = 'SE_SECIFY_log');

ALTER DATABASE SE_SECIFY MODIFY FILE (NAME = 'SE_SECIFY', FILENAME = 'C:\\Program Files\\Microsoft SQL Server\\MSSQL16.SQLEXPRESS\\MSSQL\\DATA\\SE_SECIFY.mdf');
ALTER DATABASE SE_SECIFY MODIFY FILE (NAME = 'SE_SECIFY_log', FILENAME = 'C:\\Program Files\\Microsoft SQL Server\\MSSQL16.SQLEXPRESS\\MSSQL\\DATA\\SE_SECIFY_log.ldf');