CREATE TABLE [NEGOCIO].[LIBRO_SEMAFORO] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [ID_LIBRO]   INT           NOT NULL,
    [ID_USUARIO] INT           NOT NULL,
    [FECHA]      DATETIME2 (7) NOT NULL,
    CONSTRAINT [PK_LIBRO_SEMAFORO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AK_LIBRO_SEMAFORO] UNIQUE NONCLUSTERED ([ID_LIBRO] ASC)
);

