CREATE TABLE [NEGOCIO].[LIBRO] (
    [ID]         INT IDENTITY (1, 1) NOT NULL,
    [EJERCICIO]  INT NOT NULL,
    [ID_NEGOCIO] INT NOT NULL,
    [ID_CG]      INT NOT NULL,
    [ID_TIPO]    INT NOT NULL,
    [VALOR]      INT NOT NULL,
    CONSTRAINT [PK_LIBRO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AK_LIBRO] UNIQUE NONCLUSTERED ([EJERCICIO] ASC, [ID_NEGOCIO] ASC, [ID_CG] ASC, [ID_TIPO] ASC)
);

