CREATE TABLE [NEGOCIO].[NEGOCIO] (
    [ID]                    INT           IDENTITY (1, 1) NOT NULL,
    [ELEMENTO_DTM]          VARCHAR (250) NOT NULL,
    [ICONO]                 VARCHAR (250) NULL,
    [ACTIVO]                BIT           NOT NULL,
    [ID_GESTOR]             INT           NOT NULL,
    [ID_CONSULTOR]          INT           NOT NULL,
    [ID_ADM]                INT           NOT NULL,
    [NOMBRE]                VARCHAR (250) NOT NULL,
    [ELEMENTO_DTO]          VARCHAR (250) NULL,
    [ENUMERADO]             VARCHAR (250) DEFAULT ('') NOT NULL,
    [ES_DE_PARAMETRIZACION] BIT           NOT NULL,
    [USA_SEGURIDAD]         BIT           NOT NULL,
    [USA_CG]                BIT           NOT NULL,
    CONSTRAINT [PK_NEGOCIO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_NEGOCIO_ID_ADM] FOREIGN KEY ([ID_ADM]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_NEGOCIO_ID_CONSULTOR] FOREIGN KEY ([ID_CONSULTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_NEGOCIO_ID_GESTOR] FOREIGN KEY ([ID_GESTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_NEGOCIO_ID_ADM]
    ON [NEGOCIO].[NEGOCIO]([ID_ADM] ASC);


GO
CREATE NONCLUSTERED INDEX [I_NEGOCIO_ID_CONSULTOR]
    ON [NEGOCIO].[NEGOCIO]([ID_CONSULTOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_NEGOCIO_ID_GESTOR]
    ON [NEGOCIO].[NEGOCIO]([ID_GESTOR] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_NEGOCIO_NOMBRE]
    ON [NEGOCIO].[NEGOCIO]([NOMBRE] ASC);

