CREATE TABLE [NEGOCIO].[PARAMETRO] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [VALOR]      VARCHAR (250) NOT NULL,
    [ID_NEGOCIO] INT           NOT NULL,
    [NOMBRE]     VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_PARAMETRO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_NEGOCIO_PARAMETRO_ID_NEGOCIO] FOREIGN KEY ([ID_NEGOCIO]) REFERENCES [NEGOCIO].[NEGOCIO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_NEGOCIO_ID_NEGOCIO_NOMBRE]
    ON [NEGOCIO].[PARAMETRO]([ID_NEGOCIO] ASC, [NOMBRE] ASC);

