CREATE TABLE [NEGOCIO].[SEMAFORO_PROCESO] (
    [ID]          INT              IDENTITY (1, 1) NOT NULL,
    [ID_NEGOCIO]  INT              NOT NULL,
    [ID_ELEMENTO] INT              NOT NULL,
    [OPERACION]   VARCHAR (4)      NOT NULL,
    [LOGIN]       VARCHAR (50)     NULL,
    [ANOTACION]   VARCHAR (250)    NULL,
    [FECHA]       DATETIME2 (7)    NOT NULL,
    [ID_PROCESO]  UNIQUEIDENTIFIER DEFAULT ('00000000-0000-0000-0000-000000000000') NOT NULL,
    CONSTRAINT [PK_SEMAFORO_PROCESO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AK_SEMAFORO_PROCESO] UNIQUE NONCLUSTERED ([ID_NEGOCIO] ASC, [ID_ELEMENTO] ASC)
);

