SELECT COUNT(*) AS Total
FROM CALLEJERO.CALLE c
WHERE c.NOMBRE COLLATE Latin1_General_BIN <> ENTORNO.CapitalizarFrase(c.NOMBRE) COLLATE Latin1_General_BIN;

SELECT c.ID, c.NOMBRE, ENTORNO.CapitalizarFrase(c.NOMBRE) AS NOMBRE_CAPITALIZADO
FROM CALLEJERO.CALLE c
WHERE c.NOMBRE COLLATE Latin1_General_BIN <> ENTORNO.CapitalizarFrase(c.NOMBRE) COLLATE Latin1_General_BIN
ORDER BY c.NOMBRE;