CREATE TABLE [SEGURIDAD].[CLASE_PERMISO] (
    [ID]     INT          IDENTITY (1, 1) NOT NULL,
    [NOMBRE] VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_CLASE_PERMISO] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_CLASE_PERMISO_NOMBRE]
    ON [SEGURIDAD].[CLASE_PERMISO]([NOMBRE] ASC);

