CREATE TABLE [SEGURIDAD].[PERMISO_POR_NEGOCIOS_CG] (
    [ID]         INT IDENTITY (1, 1) NOT NULL,
    [ID_NEGOCIO] INT NOT NULL,
    [ID_CG]      INT NOT NULL,
    [ID_USUARIO] INT NOT NULL,
    [ID_PERMISO] INT NOT NULL,
    CONSTRAINT [PK_PERMISO_POR_NEGOCIOS_CG] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AK_PERMISO_POR_NEGOCIOS_CG] UNIQUE NONCLUSTERED ([ID_NEGOCIO] ASC, [ID_CG] ASC, [ID_USUARIO] ASC, [ID_PERMISO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_PERMISO_POR_NEGOCIOS_CG_ID_NEGOCIO_ID_CG]
    ON [SEGURIDAD].[PERMISO_POR_NEGOCIOS_CG]([ID_NEGOCIO] ASC, [ID_CG] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PERMISO_POR_NEGOCIOS_CG_ID_NEGOCIO_ID_USUARIO_ID_PERMISO]
    ON [SEGURIDAD].[PERMISO_POR_NEGOCIOS_CG]([ID_NEGOCIO] ASC, [ID_USUARIO] ASC, [ID_PERMISO] ASC);

