CREATE TABLE [SEGURIDAD].[PERMISO] (
    [ID]      INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]  VARCHAR (250) NOT NULL,
    [IDCLASE] INT           DEFAULT ((0)) NOT NULL,
    [IDTIPO]  INT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PERMISO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PERMISO_IDCLASE] FOREIGN KEY ([IDCLASE]) REFERENCES [SEGURIDAD].[CLASE_PERMISO] ([ID]),
    CONSTRAINT [FK_PERMISO_IDTIPO] FOREIGN KEY ([IDTIPO]) REFERENCES [SEGURIDAD].[TIPO_PERMISO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_PERMISO_NOMBRE]
    ON [SEGURIDAD].[PERMISO]([NOMBRE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PERMISO_IDTIPO]
    ON [SEGURIDAD].[PERMISO]([IDTIPO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PERMISO_IDCLASE_IDTIPO]
    ON [SEGURIDAD].[PERMISO]([IDCLASE] ASC, [IDTIPO] ASC);

