CREATE TABLE [SEGURIDAD].[PERMISO_POR_NEGOCIO] (
    [ID]         INT IDENTITY (1, 1) NOT NULL,
    [ID_NEGOCIO] INT NOT NULL,
    [ID_USUARIO] INT NOT NULL,
    [ID_PERMISO] INT NOT NULL,
    [CALCULADO]  BIT DEFAULT (CONVERT([bit],(0))) NOT NULL,
    CONSTRAINT [PK_PERMISO_POR_NEGOCIO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PERMISO_POR_NEGOCIO_ID_NEGOCIO] FOREIGN KEY ([ID_NEGOCIO]) REFERENCES [NEGOCIO].[NEGOCIO] ([ID]),
    CONSTRAINT [FK_PERMISO_POR_NEGOCIO_ID_PERMISO] FOREIGN KEY ([ID_PERMISO]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_PERMISO_POR_NEGOCIO_ID_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [AK_PERMISO_POR_NEGOCIO] UNIQUE NONCLUSTERED ([ID_NEGOCIO] ASC, [ID_USUARIO] ASC, [ID_PERMISO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_PERMISO_POR_NEGOCIO_ID_NEGOCIO_ID_USUARIO]
    ON [SEGURIDAD].[PERMISO_POR_NEGOCIO]([ID_NEGOCIO] ASC, [ID_USUARIO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PERMISO_POR_NEGOCIO_ID_NEGOCIO]
    ON [SEGURIDAD].[PERMISO_POR_NEGOCIO]([ID_NEGOCIO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PERMISO_POR_NEGOCIO_ID_PERMISO]
    ON [SEGURIDAD].[PERMISO_POR_NEGOCIO]([ID_PERMISO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PERMISO_POR_NEGOCIO_ID_USUARIO]
    ON [SEGURIDAD].[PERMISO_POR_NEGOCIO]([ID_USUARIO] ASC);

