CREATE TABLE [SEGURIDAD].[PERMISO_DIRECTOS] (
    [ID]        INT IDENTITY (1, 1) NOT NULL,
    [IDPUESTO]  INT NOT NULL,
    [IDPERMISO] INT NOT NULL,
    CONSTRAINT [PK_PERMISO_DIRECTOS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PERMISO_DIRECTOS_IDPERMISO] FOREIGN KEY ([IDPERMISO]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_PERMISO_DIRECTOS_IDPUESTO] FOREIGN KEY ([IDPUESTO]) REFERENCES [SEGURIDAD].[PUESTO] ([ID]),
    CONSTRAINT [AK_PERMISO_DIRECTOS] UNIQUE NONCLUSTERED ([IDPUESTO] ASC, [IDPERMISO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_PERMISO_DIRECTOS_IDPERMISO]
    ON [SEGURIDAD].[PERMISO_DIRECTOS]([IDPERMISO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PERMISO_DIRECTOS_IDPUESTO]
    ON [SEGURIDAD].[PERMISO_DIRECTOS]([IDPUESTO] ASC);

