CREATE TABLE [SEGURIDAD].[PUESTO] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [NOMBRE]      VARCHAR (250)  NOT NULL,
    [DESCRIPCION] VARCHAR (2000) NULL,
    [ROLES]       AS             ([SEGURIDAD].[OBTENER_ROLES_DE_UN_PUESTO]([id])),
    [ID_CG]       INT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PUESTO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PUESTO_ID_CG] FOREIGN KEY ([ID_CG]) REFERENCES [TERCEROS].[CENTRO_GESTOR] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_PUESTO_NOMBRE]
    ON [SEGURIDAD].[PUESTO]([NOMBRE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PUESTO_ID_CG]
    ON [SEGURIDAD].[PUESTO]([ID_CG] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_PUESTO_ID_CG_NOMBRE]
    ON [SEGURIDAD].[PUESTO]([ID_CG] ASC, [NOMBRE] ASC);

