CREATE TABLE [SEGURIDAD].[ROL] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [NOMBRE]      VARCHAR (250)  NOT NULL,
    [DESCRIPCION] VARCHAR (2000) NULL,
    CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ROL_NOMBRE]
    ON [SEGURIDAD].[ROL]([NOMBRE] ASC);

