CREATE TABLE [SEGURIDAD].[ROL_PUESTO] (
    [ID]       INT IDENTITY (1, 1) NOT NULL,
    [IDROL]    INT NOT NULL,
    [IDPUESTO] INT NOT NULL,
    CONSTRAINT [PK_ROL_PUESTO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ROL_PUESTO_IDPUESTO] FOREIGN KEY ([IDPUESTO]) REFERENCES [SEGURIDAD].[PUESTO] ([ID]),
    CONSTRAINT [FK_ROL_PUESTO_IDROL] FOREIGN KEY ([IDROL]) REFERENCES [SEGURIDAD].[ROL] ([ID]),
    CONSTRAINT [AK_ROL_PUESTO] UNIQUE NONCLUSTERED ([IDROL] ASC, [IDPUESTO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_ROL_PUESTO_IDPUESTO]
    ON [SEGURIDAD].[ROL_PUESTO]([IDPUESTO] ASC);

