CREATE TABLE [SEGURIDAD].[ROL_PERMISO] (
    [ID]        INT IDENTITY (1, 1) NOT NULL,
    [IDROL]     INT NOT NULL,
    [IDPERMISO] INT NOT NULL,
    CONSTRAINT [PK_ROL_PERMISO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ROL_PERMISO_IDPERMISO] FOREIGN KEY ([IDPERMISO]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_ROL_PERMISO_IDROL] FOREIGN KEY ([IDROL]) REFERENCES [SEGURIDAD].[ROL] ([ID]),
    CONSTRAINT [AK_ROL_PERMISO] UNIQUE NONCLUSTERED ([IDROL] ASC, [IDPERMISO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_ROL_PERMISO_IDPERMISO]
    ON [SEGURIDAD].[ROL_PERMISO]([IDPERMISO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ROL_PERMISO_IDROL]
    ON [SEGURIDAD].[ROL_PERMISO]([IDROL] ASC);

