CREATE TABLE [SEGURIDAD].[TIPO_PERMISO] (
    [ID]     INT          IDENTITY (1, 1) NOT NULL,
    [NOMBRE] VARCHAR (30) NOT NULL,
    CONSTRAINT [PK_TIPO_PERMISO] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_TIPO_PERMISO_NOMBRE]
    ON [SEGURIDAD].[TIPO_PERMISO]([NOMBRE] ASC);

