CREATE TABLE [SEGURIDAD].[USU_PUESTO] (
    [ID]       INT IDENTITY (1, 1) NOT NULL,
    [IDUSUA]   INT NOT NULL,
    [IDPUESTO] INT NOT NULL,
    [ROLES]    AS  ([SEGURIDAD].[OBTENER_ROLES_DE_UN_PUESTO]([idPuesto])),
    CONSTRAINT [PK_USU_PUESTO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_USU_PUESTO_IDPUESTO] FOREIGN KEY ([IDPUESTO]) REFERENCES [SEGURIDAD].[PUESTO] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_USU_PUESTO_IDUSUA] FOREIGN KEY ([IDUSUA]) REFERENCES [ENTORNO].[USUARIO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_USU_PUESTO_IDUSUA]
    ON [SEGURIDAD].[USU_PUESTO]([IDUSUA] ASC);


GO
CREATE NONCLUSTERED INDEX [I_USU_PUESTO_IDPUESTO]
    ON [SEGURIDAD].[USU_PUESTO]([IDPUESTO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_USU_PUESTO_IDPUESTO_IDUSUA]
    ON [SEGURIDAD].[USU_PUESTO]([IDPUESTO] ASC, [IDUSUA] ASC);

