//GET https://biwe.femdek.com/Facturador/epSolicitarPdf

//GET https://localhost:44396/Facturador/epSolicitarPdf

### Solicitar la URL de descarga del PDF de una factura ya emitida
GET https://localhost:44396/Facturador/epSolicitarPdf?nif=00811725D&apiKey=fQ-jaqqRGffT36KfISovB2n3XwxWhCWdKd7iYZDO0ng&numeroFactura=2026-S-13&guid=07abe204-1757-4ac3-951f-9c6e3d1829bc

###

// La respuesta trae en "Datos" una URL de descarga válida 1 hora, por ejemplo:
// GET https://biwe.femdek.com/Archivos/epDescargaConGuid?guid=...&id=...
