CREATE FUNCTION [ENTORNO].[ARBOL_MENU] 
(
)
RETURNS TABLE 
AS
RETURN 
(
     WITH menuPadre 
     AS
     (
      SELECT T1.ID, T1.NOMBRE, T1.DESCRIPCION, T1.ICONO, T1.ACTIVO, T1.IDPADRE,  T1.IDVISTA_MVC, T1.ORDEN, t1.PARAMETROS
      FROM entorno.MENU T1
      UNION ALL
       --RECURSIVIDAD
      SELECT S1.ID, S1.NOMBRE, S1.DESCRIPCION, S1.ICONO, S1.ACTIVO, S1.IDPADRE,  S1.IDVISTA_MVC, S1.ORDEN, t1.PARAMETROS
      FROM ENTORNO.MENU AS S1 
      INNER JOIN menuPadre AS T1 ON S1.IDPADRE = T1.id
     )
     SELECT DISTINCT P1.ID, P1.NOMBRE, P1.DESCRIPCION, P1.ICONO, P1.ACTIVO, P1.IDPADRE, P1.IDVISTA_MVC, P1.ORDEN, P1.PARAMETROS
     FROM menuPadre AS P1
)
