CREATE VIEW[ENTORNO].[USUARIO_PERMISO]
AS
select CAST(ROW_NUMBER() OVER(ORDER BY IDUSUA ASC) as int) AS ID, IDUSUA, IDPERMISO, SEGURIDAD.OBTENER_ORIGEN (IDUSUA, IDPERMISO) as ORIGEN
from (
    select  t2.IDUSUA as IDUSUA, t4.IDPERMISO as IDPERMISO 
    from SEGURIDAD.USU_PUESTO t2
    inner join SEGURIDAD.ROL_PUESTO T3 ON T3.IDPUESTO = T2.IDPUESTO
    INNER JOIN SEGURIDAD.ROL_PERMISO T4 ON T4.IDROL = T3.IDROL
 union all
  select t2.IDUSUA as IDUSUA, t1.IDPERMISO as IDPERMISO
  from SEGURIDAD.USU_PUESTO t2
  inner join SEGURIDAD.PERMISO_DIRECTOS t1 on t1.IDPUESTO = t2.IDPUESTO
 ) Permisos
 group by IDUSUA, IDPERMISO
