CREATE TABLE [ENTORNO].[ACCION] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [CLASE_DE_ACCION] VARCHAR (4)    NOT NULL,
    [DLL]             VARCHAR (250)  NULL,
    [CLASE]           VARCHAR (250)  NULL,
    [METODO]          VARCHAR (250)  NULL,
    [ESQUEMA]         VARCHAR (250)  NULL,
    [PA]              VARCHAR (250)  NULL,
    [SQL]             VARCHAR (2000) NULL,
    [DESCRIPCION]     VARCHAR (2000) NULL,
    [NOMBRE]          VARCHAR (250)  NOT NULL,
    CONSTRAINT [PK_ACCION] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ACCION_POR_ACCION]
    ON [ENTORNO].[ACCION]([DLL] ASC, [CLASE] ASC, [METODO] ASC, [ESQUEMA] ASC, [PA] ASC, [SQL] ASC) WHERE ([DLL] IS NOT NULL AND [CLASE] IS NOT NULL AND [METODO] IS NOT NULL AND [ESQUEMA] IS NOT NULL AND [PA] IS NOT NULL AND [SQL] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [I_ACCION_NOMBRE]
    ON [ENTORNO].[ACCION]([NOMBRE] ASC);

