CREATE TABLE [ENTORNO].[MENU] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [NOMBRE]      VARCHAR (250)  NOT NULL,
    [DESCRIPCION] VARCHAR (2000) NULL,
    [ICONO]       VARCHAR (250)  NOT NULL,
    [ACTIVO]      BIT            NOT NULL,
    [IDPADRE]     INT            NULL,
    [IDVISTA_MVC] INT            NULL,
    [ORDEN]       INT            DEFAULT ((0)) NOT NULL,
    [PARAMETROS]  VARCHAR (2000) NULL,
    CONSTRAINT [PK_MENU] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MENU_IDPADRE] FOREIGN KEY ([IDPADRE]) REFERENCES [ENTORNO].[MENU] ([ID]),
    CONSTRAINT [FK_MENU_IDVISTA_MVC] FOREIGN KEY ([IDVISTA_MVC]) REFERENCES [ENTORNO].[VISTA_MVC] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_MENU_ID_PADRE_NOMBRE]
    ON [ENTORNO].[MENU]([IDPADRE] ASC, [NOMBRE] ASC) WHERE ([IDPADRE] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [IX_MENU_IDVISTA_MVC]
    ON [ENTORNO].[MENU]([IDVISTA_MVC] ASC);

