CREATE TABLE [ENTORNO].[USUARIO] (
    [ID]            INT           IDENTITY (1, 1) NOT NULL,
    [LOGIN]         VARCHAR (50)  NOT NULL,
    [APELLIDO]      VARCHAR (250) NOT NULL,
    [NOMBRE]        VARCHAR (50)  NOT NULL,
    [F_ALTA]        DATE          NOT NULL,
    [ID_ARCHIVO]    INT           NULL,
    [PASSWORD]      VARCHAR (250) NOT NULL,
    [ADMINISTRADOR] BIT           DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [EMAIL]         VARCHAR (50)  DEFAULT ('pendiente@se.com') NOT NULL,
    CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_USUARIO_ID_ARCHIVO] FOREIGN KEY ([ID_ARCHIVO]) REFERENCES [SISDOC].[ARCHIVO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_USUARIO]
    ON [ENTORNO].[USUARIO]([LOGIN] ASC);


GO
CREATE NONCLUSTERED INDEX [I_USUARIO_ID_ARCHIVO]
    ON [ENTORNO].[USUARIO]([ID_ARCHIVO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_USUARIO_NOMBRE]
    ON [ENTORNO].[USUARIO]([NOMBRE] ASC);

