CREATE TABLE [ENTORNO].[VARIABLE] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]      VARCHAR (50)  NOT NULL,
    [DESCRIPCION] VARCHAR (MAX) NULL,
    [VALOR]       VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_VARIABLE] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_VARIABLE_NOMBRE]
    ON [ENTORNO].[VARIABLE]([NOMBRE] ASC);

