CREATE TABLE [ENTORNO].[VISTA_MVC] (
    [ID]           INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]       VARCHAR (250) NOT NULL,
    [CONTROLADOR]  VARCHAR (250) NOT NULL,
    [ACCION]       VARCHAR (250) NOT NULL,
    [PARAMETROS]   VARCHAR (250) NULL,
    [MODAL]        BIT           NOT NULL,
    [IDPERMISO]    INT           NOT NULL,
    [ELEMENTO_DTO] VARCHAR (250) NULL,
    CONSTRAINT [PK_VISTA_MVC] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_VISTA_MVC_IDPERMISO] FOREIGN KEY ([IDPERMISO]) REFERENCES [SEGURIDAD].[PERMISO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_VISTA_MVC_NOMBRE]
    ON [ENTORNO].[VISTA_MVC]([NOMBRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_VISTA_MVC_CONTROLADOR_ACCION]
    ON [ENTORNO].[VISTA_MVC]([CONTROLADOR] ASC, [ACCION] ASC, [PARAMETROS] ASC) WHERE ([PARAMETROS] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_VISTA_MVC_IDPERMISO]
    ON [ENTORNO].[VISTA_MVC]([IDPERMISO] ASC);

