CREATE TABLE [SISDOC].[ARCHIVO_SINCRONIZADO] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [ID_ARCHIVO]      INT           NOT NULL,
    [RUTA]            VARCHAR (MAX) NOT NULL,
    [PROPIETARIO]     VARCHAR (50)  NOT NULL,
    [CREADO_EL]       DATETIME2 (7) NOT NULL,
    [MODIFICADO_EL]   DATETIME2 (7) NOT NULL,
    [SINCRONIZADO_EL] DATETIME2 (7) NOT NULL,
    [LONGITUD]        BIGINT        NOT NULL,
    CONSTRAINT [PK_ARCHIVO_SINCRONIZADO] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ARCHIVO_SINCRONIZADO_ID_ARCHIVO]
    ON [SISDOC].[ARCHIVO_SINCRONIZADO]([ID_ARCHIVO] ASC);

