CREATE TABLE [SISDOC].[ARCHIVADOR_ARCHIVO] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO1] INT NOT NULL,
    [ID_ELEMENTO2] INT NOT NULL,
    CONSTRAINT [PK_ARCHIVADOR_ARCHIVO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ARCHIVADOR_ARCHIVO_ID_ELEMENTO1] FOREIGN KEY ([ID_ELEMENTO1]) REFERENCES [SISDOC].[ARCHIVADOR] ([ID]),
    CONSTRAINT [FK_ARCHIVADOR_ARCHIVO_ID_ELEMENTO2] FOREIGN KEY ([ID_ELEMENTO2]) REFERENCES [SISDOC].[ARCHIVO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_ARCHIVO_ID_ELEMENTO1]
    ON [SISDOC].[ARCHIVADOR_ARCHIVO]([ID_ELEMENTO1] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_ARCHIVO_ID_ELEMENTO2]
    ON [SISDOC].[ARCHIVADOR_ARCHIVO]([ID_ELEMENTO2] ASC);

