CREATE TABLE [SISDOC].[ARCHIVO] (
    [ID]             INT            IDENTITY (1, 1) NOT NULL,
    [FECCRE]         DATETIME2 (7)  NOT NULL,
    [ID_CREADOR]     INT            NOT NULL,
    [FECMOD]         DATETIME2 (7)  NULL,
    [ID_MODIFICADOR] INT            NULL,
    [NOMBRE]         VARCHAR (250)  NOT NULL,
    [RUTA]           VARCHAR (2000) NOT NULL,
    CONSTRAINT [PK_ARCHIVO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ARCHIVO_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_ARCHIVO_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVO_ID_CREADOR]
    ON [SISDOC].[ARCHIVO]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVO_ID_MODIFICADOR]
    ON [SISDOC].[ARCHIVO]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVO_NOMBRE]
    ON [SISDOC].[ARCHIVO]([NOMBRE] ASC);

