CREATE TABLE [SISDOC].[ARCHIVADOR] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [ID_CG]           INT            NOT NULL,
    [ID_TIPO]         INT            NOT NULL,
    [DESCRIPCION]     VARCHAR (2000) NULL,
    [REFERENCIA]      VARCHAR (20)   NOT NULL,
    [BAJA]            BIT            DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [NOMBRE]          VARCHAR (250)  NOT NULL,
    [FECCRE]          DATETIME2 (7)  NOT NULL,
    [ID_CREADOR]      INT            NOT NULL,
    [FECMOD]          DATETIME2 (7)  NULL,
    [ID_MODIFICADOR]  INT            NULL,
    [SINCRONIZAR_CON] VARCHAR (250)  NULL,
    CONSTRAINT [PK_ARCHIVADOR] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ARCHIVADOR_ID_CG] FOREIGN KEY ([ID_CG]) REFERENCES [TERCEROS].[CENTRO_GESTOR] ([ID]),
    CONSTRAINT [FK_ARCHIVADOR_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_ARCHIVADOR_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_ARCHIVADOR_ID_TIPO] FOREIGN KEY ([ID_TIPO]) REFERENCES [SISDOC].[ARCHIVADOR_TIPO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_ID_CG]
    ON [SISDOC].[ARCHIVADOR]([ID_CG] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_ID_CREADOR]
    ON [SISDOC].[ARCHIVADOR]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_ID_MODIFICADOR]
    ON [SISDOC].[ARCHIVADOR]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_ID_TIPO]
    ON [SISDOC].[ARCHIVADOR]([ID_TIPO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_NOMBRE]
    ON [SISDOC].[ARCHIVADOR]([NOMBRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ARCHIVADOR_REFERENCIA]
    ON [SISDOC].[ARCHIVADOR]([REFERENCIA] ASC);

