CREATE TABLE [SISDOC].[ARCHIVADOR_AUDITORIA] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO] INT           NOT NULL,
    [ID_USUARIO]  INT           NOT NULL,
    [OPERACION]   CHAR (1)      NOT NULL,
    [REGISTRO]    VARCHAR (MAX) NOT NULL,
    [AUDITADO_EL] DATETIME2 (7) NOT NULL,
    CONSTRAINT [PK_ARCHIVADOR_AUDITORIA] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_AUDITORIA_ID_ELEMENTO]
    ON [SISDOC].[ARCHIVADOR_AUDITORIA]([ID_ELEMENTO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_AUDITORIA_ID_USUARIO]
    ON [SISDOC].[ARCHIVADOR_AUDITORIA]([ID_USUARIO] ASC);

