CREATE TABLE [SISDOC].[ARCHIVADOR_TIPO] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [VISIBLE]        BIT           NOT NULL,
    [NOMBRE]         VARCHAR (250) NOT NULL,
    [ID_PADRE]       INT           NULL,
    [ID_GESTOR]      INT           NOT NULL,
    [ID_CONSULTOR]   INT           NOT NULL,
    [ID_ADM]         INT           NOT NULL,
    [ACTIVO]         BIT           NOT NULL,
    [TIPO_DTM]       VARCHAR (250) NOT NULL,
    [TIPO_DTO]       VARCHAR (250) NOT NULL,
    [CLASE_DE_LIBRO] VARCHAR (20)  NOT NULL,
    [SIGLA]          VARCHAR (5)   DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_ARCHIVADOR_TIPO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ARCHIVADOR_TIPO_ID_ADM] FOREIGN KEY ([ID_ADM]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_ARCHIVADOR_TIPO_ID_CONSULTOR] FOREIGN KEY ([ID_CONSULTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_ARCHIVADOR_TIPO_ID_GESTOR] FOREIGN KEY ([ID_GESTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_ARCHIVADOR_TIPO_ID_PADRE] FOREIGN KEY ([ID_PADRE]) REFERENCES [SISDOC].[ARCHIVADOR_TIPO] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ARCHIVADOR_TIPO_ID_ADM]
    ON [SISDOC].[ARCHIVADOR_TIPO]([ID_ADM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ARCHIVADOR_TIPO_ID_CONSULTOR]
    ON [SISDOC].[ARCHIVADOR_TIPO]([ID_CONSULTOR] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ARCHIVADOR_TIPO_ID_GESTOR]
    ON [SISDOC].[ARCHIVADOR_TIPO]([ID_GESTOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_ARCHIVADOR_TIPO_ID_PADRE]
    ON [SISDOC].[ARCHIVADOR_TIPO]([ID_PADRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_ARCHIVADOR_TIPO_NOMBRE]
    ON [SISDOC].[ARCHIVADOR_TIPO]([NOMBRE] ASC);

