CREATE TABLE [SISDOC].[CARPETA] (
    [ID]            INT           IDENTITY (1, 1) NOT NULL,
    [ID_ARCHIVADOR] INT           NOT NULL,
    [ID_PADRE]      INT           NULL,
    [NOMBRE]        VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_CARPETA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CARPETA_ID_ARCHIVADOR] FOREIGN KEY ([ID_ARCHIVADOR]) REFERENCES [SISDOC].[ARCHIVADOR] ([ID]),
    CONSTRAINT [FK_CARPETA_ID_PADRE] FOREIGN KEY ([ID_PADRE]) REFERENCES [SISDOC].[CARPETA] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_CARPETA_ID_ARCHIVADOR]
    ON [SISDOC].[CARPETA]([ID_ARCHIVADOR] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_CARPETA_ID_ARCHIVADOR_ID_PADRE_NOMBRE]
    ON [SISDOC].[CARPETA]([ID_ARCHIVADOR] ASC, [ID_PADRE] ASC, [NOMBRE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CARPETA_ID_PADRE]
    ON [SISDOC].[CARPETA]([ID_PADRE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CARPETA_NOMBRE]
    ON [SISDOC].[CARPETA]([NOMBRE] ASC);

