
CREATE TABLE [ENTORNO].[VISTA_MVC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NOT NULL,
	[CONTROLADOR] [varchar](250) NOT NULL,
	[ACCION] [varchar](250) NOT NULL,
	[PARAMETROS] [varchar](250) NULL,
 CONSTRAINT [PK_VISTA_MVC] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [ENTORNO].[MENU](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NOT NULL,
	[DESCRIPCION] [varchar](max) NULL,
	[ICONO] [varchar](250) NOT NULL,
	[ACTIVO] [bit] NOT NULL,
	[IDPADRE] [int] NULL,
	[IDVISTA_MVC] [int] NULL,
	[ORDEN] [int] NOT NULL,
 CONSTRAINT [PK_MENU] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [ENTORNO].[MENU] ADD  DEFAULT ((0)) FOR [ORDEN]
GO

ALTER TABLE [ENTORNO].[MENU]  WITH CHECK ADD  CONSTRAINT [FK_MENU_IDPADRE] FOREIGN KEY([IDPADRE])
REFERENCES [ENTORNO].[MENU] ([ID])
GO

ALTER TABLE [ENTORNO].[MENU] CHECK CONSTRAINT [FK_MENU_IDPADRE]
GO

ALTER TABLE [ENTORNO].[MENU]  WITH CHECK ADD  CONSTRAINT [FK_MENU_IDVISTA_MVC] FOREIGN KEY([IDVISTA_MVC])
REFERENCES [ENTORNO].[VISTA_MVC] ([ID])
GO

ALTER TABLE [ENTORNO].[MENU] CHECK CONSTRAINT [FK_MENU_IDVISTA_MVC]
GO

CREATE TABLE [ENTORNO].[USUARIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LOGIN] [varchar](50) NOT NULL,
	[APELLIDO] [varchar](250) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[F_ALTA] [date] NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [ENTORNO].[VARIABLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](max) NULL,
	[VALOR] [varchar](50) NOT NULL,
 CONSTRAINT [PK_VARIABLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE VIEW ENTORNO.USU_PERMISO
AS
select distinct t2.IDUSUA as IDUSUA, t4.IDPERMISO as IDPERMISO
from SEGURIDAD.USU_PUESTO t2 
inner join SEGURIDAD.ROL_PUESTO T3 ON T3.IDPUESTO = T2.IDPUESTO
INNER JOIN SEGURIDAD.ROL_PERMISO T4 ON T4.IDROL = T3.IDROL

