CREATE TABLE [SEGURIDAD].[PERMISO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NOT NULL,
	[CLASE] [varchar](30) NOT NULL,
	[PERMISO] [varchar](30) NOT NULL,
 CONSTRAINT [PK_PERMISO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_PERMISO_NOMBRE] UNIQUE NONCLUSTERED 
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [SEGURIDAD].[ROL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NOT NULL,
	[DESCRIPCION] [varchar](max) NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_ROL_NOMBRE] UNIQUE NONCLUSTERED 
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [SEGURIDAD].[PUESTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](250) NOT NULL,
	[DESCRIPCION] [varchar](max) NULL,
 CONSTRAINT [PK_PUESTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_PUESTO_NOMBRE] UNIQUE NONCLUSTERED 
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [SistemaDeElementos]
GO

CREATE TABLE [SEGURIDAD].[ROL_PERMISO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDROL] [int] NOT NULL,
	[IDPERMISO] [int] NOT NULL,
 CONSTRAINT [PK_ROL_PERMISO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_ROL_PERMISO] UNIQUE NONCLUSTERED 
(
	[IDROL] ASC,
	[IDPERMISO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SEGURIDAD].[ROL_PERMISO]  WITH CHECK ADD  CONSTRAINT [FK_ROL_PERMISO_IDPERMISO] FOREIGN KEY([IDPERMISO])
REFERENCES [SEGURIDAD].[PERMISO] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [SEGURIDAD].[ROL_PERMISO] CHECK CONSTRAINT [FK_ROL_PERMISO_IDPERMISO]
GO

ALTER TABLE [SEGURIDAD].[ROL_PERMISO]  WITH CHECK ADD  CONSTRAINT [FK_ROL_PERMISO_IDROL] FOREIGN KEY([IDROL])
REFERENCES [SEGURIDAD].[ROL] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [SEGURIDAD].[ROL_PERMISO] CHECK CONSTRAINT [FK_ROL_PERMISO_IDROL]
GO

USE [SistemaDeElementos]
GO

CREATE TABLE [SEGURIDAD].[ROL_PUESTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDROL] [int] NOT NULL,
	[IDPUESTO] [int] NOT NULL,
 CONSTRAINT [PK_ROL_PUESTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_ROL_PUESTO] UNIQUE NONCLUSTERED 
(
	[IDROL] ASC,
	[IDPUESTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SEGURIDAD].[ROL_PUESTO]  WITH CHECK ADD  CONSTRAINT [FK_ROL_PUESTO_IDPUESTO] FOREIGN KEY([IDPUESTO])
REFERENCES [SEGURIDAD].[PUESTO] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [SEGURIDAD].[ROL_PUESTO] CHECK CONSTRAINT [FK_ROL_PUESTO_IDPUESTO]
GO

ALTER TABLE [SEGURIDAD].[ROL_PUESTO]  WITH CHECK ADD  CONSTRAINT [FK_ROL_PUESTO_IDROL] FOREIGN KEY([IDROL])
REFERENCES [SEGURIDAD].[ROL] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [SEGURIDAD].[ROL_PUESTO] CHECK CONSTRAINT [FK_ROL_PUESTO_IDROL]
GO

CREATE TABLE [SEGURIDAD].[USU_PUESTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDUSUA] [int] NOT NULL,
	[IDPUESTO] [int] NOT NULL,
 CONSTRAINT [PK_USU_PUESTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_USU_PUESTO] UNIQUE NONCLUSTERED 
(
	[IDUSUA] ASC,
	[IDPUESTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [SEGURIDAD].[USU_PUESTO]  WITH CHECK ADD  CONSTRAINT [FK_USU_PUESTO_IDPUESTO] FOREIGN KEY([IDPUESTO])
REFERENCES [SEGURIDAD].[PUESTO] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [SEGURIDAD].[USU_PUESTO] CHECK CONSTRAINT [FK_USU_PUESTO_IDPUESTO]
GO

ALTER TABLE [SEGURIDAD].[USU_PUESTO]  WITH CHECK ADD  CONSTRAINT [FK_USU_PUESTO_IDUSUA] FOREIGN KEY([IDUSUA])
REFERENCES [ENTORNO].[USUARIO] ([ID])
GO

ALTER TABLE [SEGURIDAD].[USU_PUESTO] CHECK CONSTRAINT [FK_USU_PUESTO_IDUSUA]
GO

USE [SistemaDeElementos]
GO


create view [SEGURIDAD].[V_USUARIO] as
                                    select
                                       ID,
                                       LOGIN,
                                       APELLIDO,
                                       NOMBRE
                                    from
                                       ENTORNO.USUARIO
GO










