CREATE PROCEDURE CompareDatabases
    @Database1 NVARCHAR(128),
    @Database2 NVARCHAR(128)
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX);

    SET @SQL = '
    -- Comparar Tablas
    SELECT ''Table'' AS ObjectType, t1.TABLE_SCHEMA AS SchemaName, t1.TABLE_NAME AS ObjectName
    FROM ' + QUOTENAME(@Database1) + '.INFORMATION_SCHEMA.TABLES t1
    LEFT JOIN ' + QUOTENAME(@Database2) + '.INFORMATION_SCHEMA.TABLES t2 
        ON t1.TABLE_SCHEMA = t2.TABLE_SCHEMA AND t1.TABLE_NAME = t2.TABLE_NAME
    WHERE t2.TABLE_NAME IS NULL AND t1.TABLE_TYPE = ''BASE TABLE''

    UNION ALL

    -- Comparar Vistas
    SELECT ''View'' AS ObjectType, v1.TABLE_SCHEMA AS SchemaName, v1.TABLE_NAME AS ObjectName
    FROM ' + QUOTENAME(@Database1) + '.INFORMATION_SCHEMA.VIEWS v1
    LEFT JOIN ' + QUOTENAME(@Database2) + '.INFORMATION_SCHEMA.VIEWS v2 
        ON v1.TABLE_SCHEMA = v2.TABLE_SCHEMA AND v1.TABLE_NAME = v2.TABLE_NAME
    WHERE v2.TABLE_NAME IS NULL

    UNION ALL

    -- Comparar Funciones
    SELECT ''Function'' AS ObjectType, r1.ROUTINE_SCHEMA AS SchemaName, r1.ROUTINE_NAME AS ObjectName
    FROM ' + QUOTENAME(@Database1) + '.INFORMATION_SCHEMA.ROUTINES r1
    LEFT JOIN ' + QUOTENAME(@Database2) + '.INFORMATION_SCHEMA.ROUTINES r2 
        ON r1.ROUTINE_SCHEMA = r2.ROUTINE_SCHEMA AND r1.ROUTINE_NAME = r2.ROUTINE_NAME
    WHERE r2.ROUTINE_NAME IS NULL AND r1.ROUTINE_TYPE = ''FUNCTION''

    UNION ALL

    -- Comparar Procedimientos Almacenados
    SELECT ''Stored Procedure'' AS ObjectType, r1.ROUTINE_SCHEMA AS SchemaName, r1.ROUTINE_NAME AS ObjectName
    FROM ' + QUOTENAME(@Database1) + '.INFORMATION_SCHEMA.ROUTINES r1
    LEFT JOIN ' + QUOTENAME(@Database2) + '.INFORMATION_SCHEMA.ROUTINES r2 
        ON r1.ROUTINE_SCHEMA = r2.ROUTINE_SCHEMA AND r1.ROUTINE_NAME = r2.ROUTINE_NAME
    WHERE r2.ROUTINE_NAME IS NULL AND r1.ROUTINE_TYPE = ''PROCEDURE''

    ORDER BY ObjectType, SchemaName, ObjectName;
    ';

    EXEC sp_executesql @SQL;
END;

EXEC CompareDatabases 'SE_TEST', 'SE_TEST_Back';


-- Comparar Tablas
SELECT 'Table' AS ObjectType, t1.TABLE_SCHEMA AS SchemaName, t1.TABLE_NAME AS ObjectName
FROM SE_TEST.INFORMATION_SCHEMA.TABLES t1
LEFT JOIN SE_TEST_Back.INFORMATION_SCHEMA.TABLES t2 
    ON t1.TABLE_SCHEMA = t2.TABLE_SCHEMA AND t1.TABLE_NAME = t2.TABLE_NAME
WHERE t2.TABLE_NAME IS NULL AND t1.TABLE_TYPE = 'BASE TABLE'

UNION ALL

-- Comparar Vistas
SELECT 'View' AS ObjectType, v1.TABLE_SCHEMA AS SchemaName, v1.TABLE_NAME AS ObjectName
FROM SE_TEST.INFORMATION_SCHEMA.VIEWS v1
LEFT JOIN SE_TEST_Back.INFORMATION_SCHEMA.VIEWS v2 
    ON v1.TABLE_SCHEMA = v2.TABLE_SCHEMA AND v1.TABLE_NAME = v2.TABLE_NAME
WHERE v2.TABLE_NAME IS NULL

UNION ALL

-- Comparar Funciones
SELECT 'Function' AS ObjectType, r1.ROUTINE_SCHEMA AS SchemaName, r1.ROUTINE_NAME AS ObjectName
FROM SE_TEST.INFORMATION_SCHEMA.ROUTINES r1
LEFT JOIN SE_TEST_Back.INFORMATION_SCHEMA.ROUTINES r2 
    ON r1.ROUTINE_SCHEMA = r2.ROUTINE_SCHEMA AND r1.ROUTINE_NAME = r2.ROUTINE_NAME
WHERE r2.ROUTINE_NAME IS NULL AND r1.ROUTINE_TYPE = 'FUNCTION'

UNION ALL

-- Comparar Procedimientos Almacenados
SELECT 'Stored Procedure' AS ObjectType, r1.ROUTINE_SCHEMA AS SchemaName, r1.ROUTINE_NAME AS ObjectName
FROM SE_TEST.INFORMATION_SCHEMA.ROUTINES r1
LEFT JOIN SE_TEST_Back.INFORMATION_SCHEMA.ROUTINES r2 
    ON r1.ROUTINE_SCHEMA = r2.ROUTINE_SCHEMA AND r1.ROUTINE_NAME = r2.ROUTINE_NAME
WHERE r2.ROUTINE_NAME IS NULL AND r1.ROUTINE_TYPE = 'PROCEDURE'

ORDER BY ObjectType, SchemaName, ObjectName;
