CREATE TABLE [CALLEJERO].[BARRIO] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [ID_MUNICIPIO]   INT           NOT NULL,
    [NOMBRE]         VARCHAR (250) NOT NULL,
    [FECCRE]         DATETIME2 (7) NOT NULL,
    [ID_CREADOR]     INT           NOT NULL,
    [FECMOD]         DATETIME2 (7) NULL,
    [ID_MODIFICADOR] INT           NULL,
    CONSTRAINT [PK_BARRIO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BARRIO_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_BARRIO_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_BARRIO_ID_MUNICIPIO] FOREIGN KEY ([ID_MUNICIPIO]) REFERENCES [CALLEJERO].[MUNICIPIO] ([ID]),
    CONSTRAINT [AK_BARRIO_ID_MUNICIPIO_NOMBRE] UNIQUE NONCLUSTERED ([ID_MUNICIPIO] ASC, [NOMBRE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_BARRIO_ID_MUNICIPIO]
    ON [CALLEJERO].[BARRIO]([ID_MUNICIPIO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_BARRIO_ID_CREADOR]
    ON [CALLEJERO].[BARRIO]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_BARRIO_ID_MODIFICADOR]
    ON [CALLEJERO].[BARRIO]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_BARRIO_NOMBRE]
    ON [CALLEJERO].[BARRIO]([NOMBRE] ASC);

