CREATE TABLE [CALLEJERO].[CALLE_CP] (
    [ID]       INT         IDENTITY (1, 1) NOT NULL,
    [ID_CALLE] INT         NOT NULL,
    [ID_CP]    INT         NOT NULL,
    [DESDE]    DECIMAL (5) DEFAULT ((0.0)) NOT NULL,
    [HASTA]    DECIMAL (5) DEFAULT ((99999.0)) NOT NULL,
    [MANO]     CHAR (1)    DEFAULT ('A') NOT NULL,
    CONSTRAINT [PK_CALLE_CP] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CALLE_CP_ID_CALLE] FOREIGN KEY ([ID_CALLE]) REFERENCES [CALLEJERO].[CALLE] ([ID]),
    CONSTRAINT [FK_CALLE_CP_ID_CP] FOREIGN KEY ([ID_CP]) REFERENCES [CALLEJERO].[CODIGO_POSTAL] ([ID]),
    CONSTRAINT [AK_CALLE_CP_ID_CP_ID_CALLE] UNIQUE NONCLUSTERED ([ID_CP] ASC, [ID_CALLE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_CP_ID_CALLE]
    ON [CALLEJERO].[CALLE_CP]([ID_CALLE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_CP_ID_CP]
    ON [CALLEJERO].[CALLE_CP]([ID_CP] ASC);

