CREATE TABLE [CALLEJERO].[CALLE_ZONA] (
    [ID]       INT IDENTITY (1, 1) NOT NULL,
    [ID_CALLE] INT NOT NULL,
    [ID_ZONA]  INT NOT NULL,
    CONSTRAINT [PK_CALLE_ZONA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CALLE_ZONA_ID_CALLE] FOREIGN KEY ([ID_CALLE]) REFERENCES [CALLEJERO].[CALLE] ([ID]),
    CONSTRAINT [FK_CALLE_ZONA_ID_ZONA] FOREIGN KEY ([ID_ZONA]) REFERENCES [CALLEJERO].[ZONA] ([ID]),
    CONSTRAINT [AK_CALLE_ZONA_ID_ZONA_ID_CALLE] UNIQUE NONCLUSTERED ([ID_ZONA] ASC, [ID_CALLE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_ZONA_ID_CALLE]
    ON [CALLEJERO].[CALLE_ZONA]([ID_CALLE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_ZONA_ID_ZONA]
    ON [CALLEJERO].[CALLE_ZONA]([ID_ZONA] ASC);

