CREATE TABLE [CALLEJERO].[CALLE_BARRIO] (
    [ID]        INT         IDENTITY (1, 1) NOT NULL,
    [ID_CALLE]  INT         NOT NULL,
    [ID_BARRIO] INT         NOT NULL,
    [DESDE]     DECIMAL (5) DEFAULT ((0.0)) NOT NULL,
    [HASTA]     DECIMAL (5) DEFAULT ((99999.0)) NOT NULL,
    [MANO]      CHAR (1)    DEFAULT ('A') NOT NULL,
    CONSTRAINT [PK_CALLE_BARRIO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CALLE_BARRIO_ID_BARRIO] FOREIGN KEY ([ID_BARRIO]) REFERENCES [CALLEJERO].[BARRIO] ([ID]),
    CONSTRAINT [FK_CALLE_BARRIO_ID_CALLE] FOREIGN KEY ([ID_CALLE]) REFERENCES [CALLEJERO].[CALLE] ([ID]),
    CONSTRAINT [AK_CALLE_BARRIO_ID_BARRIO_ID_CALLE] UNIQUE NONCLUSTERED ([ID_BARRIO] ASC, [ID_CALLE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_BARRIO_ID_BARRIO]
    ON [CALLEJERO].[CALLE_BARRIO]([ID_BARRIO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_BARRIO_ID_CALLE]
    ON [CALLEJERO].[CALLE_BARRIO]([ID_CALLE] ASC);

