CREATE TABLE [CALLEJERO].[CALLE] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [ID_MUNICIPIO]   INT           NOT NULL,
    [ID_TIPO_DE_VIA] INT           NOT NULL,
    [NOMBRE]         VARCHAR (250) NOT NULL,
    [FECCRE]         DATETIME2 (7) NOT NULL,
    [ID_CREADOR]     INT           NOT NULL,
    [FECMOD]         DATETIME2 (7) NULL,
    [ID_MODIFICADOR] INT           NULL,
    [EXPRESION]      AS            ([CALLEJERO].[CC_CALLE_EXPRESION]([NOMBRE],[ID_MUNICIPIO],[ID_TIPO_DE_VIA])),
    CONSTRAINT [PK_CALLE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CALLE_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_CALLE_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_CALLE_ID_MUNICIPIO] FOREIGN KEY ([ID_MUNICIPIO]) REFERENCES [CALLEJERO].[MUNICIPIO] ([ID]),
    CONSTRAINT [FK_CALLE_ID_TIPO_DE_VIA] FOREIGN KEY ([ID_TIPO_DE_VIA]) REFERENCES [CALLEJERO].[TIPO_VIA] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_CALLE_ID_MUNICIPIO_NOMBRE]
    ON [CALLEJERO].[CALLE]([ID_MUNICIPIO] ASC, [NOMBRE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_ID_MUNICIPIO]
    ON [CALLEJERO].[CALLE]([ID_MUNICIPIO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_ID_CREADOR]
    ON [CALLEJERO].[CALLE]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_ID_MODIFICADOR]
    ON [CALLEJERO].[CALLE]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_NOMBRE]
    ON [CALLEJERO].[CALLE]([NOMBRE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CALLE_ID_TIPO_VIA]
    ON [CALLEJERO].[CALLE]([ID_TIPO_DE_VIA] ASC);

