CREATE TABLE [CALLEJERO].[CODIGO_POSTAL] (
    [ID]         INT         IDENTITY (1, 1) NOT NULL,
    [CP]         VARCHAR (5) NOT NULL,
    [PROVINCIA]  AS          ([CALLEJERO].[CC_CODIGO_POSTAL_PROVINCIA]([CP])),
    [MUNICIPIOS] AS          ([CALLEJERO].[CC_CODIGO_POSTAL_MUNICIPIOS]([ID])),
    CONSTRAINT [PK_CODIGO_POSTAL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AK_CODIGO_POSTAL_CP] UNIQUE NONCLUSTERED ([CP] ASC)
);

