CREATE TABLE [CALLEJERO].[MUNICIPIO] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [DC]             VARCHAR (1)   NOT NULL,
    [ID_PROVINCIA]   INT           NOT NULL,
    [NOMBRE]         VARCHAR (250) NOT NULL,
    [FECCRE]         DATETIME2 (7) NOT NULL,
    [ID_CREADOR]     INT           NOT NULL,
    [FECMOD]         DATETIME2 (7) NULL,
    [ID_MODIFICADOR] INT           NULL,
    CONSTRAINT [PK_MUNICIPIO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MUNICIPIO_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_MUNICIPIO_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_MUNICIPIO_ID_PROVINCIA] FOREIGN KEY ([ID_PROVINCIA]) REFERENCES [CALLEJERO].[PROVINCIA] ([ID]),
    CONSTRAINT [AK_MUNICIPIO_ID_PROVINCIA_NOMBRE] UNIQUE NONCLUSTERED ([ID_PROVINCIA] ASC, [NOMBRE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_MUNICIPIO_ID_PROVINCIA]
    ON [CALLEJERO].[MUNICIPIO]([ID_PROVINCIA] ASC);


GO
CREATE NONCLUSTERED INDEX [I_MUNICIPIO_ID_CREADOR]
    ON [CALLEJERO].[MUNICIPIO]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_MUNICIPIO_ID_MODIFICADOR]
    ON [CALLEJERO].[MUNICIPIO]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_MUNICIPIO_NOMBRE]
    ON [CALLEJERO].[MUNICIPIO]([NOMBRE] ASC);

