CREATE TABLE [CALLEJERO].[MUNICIPIO_CP] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_MUNICIPIO] INT NOT NULL,
    [ID_CP]        INT NOT NULL,
    CONSTRAINT [PK_MUNICIPIO_CP] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MUNICIPIO_CP_ID_CP] FOREIGN KEY ([ID_CP]) REFERENCES [CALLEJERO].[CODIGO_POSTAL] ([ID]),
    CONSTRAINT [FK_MUNICIPIO_CP_ID_MUNICIPIO] FOREIGN KEY ([ID_MUNICIPIO]) REFERENCES [CALLEJERO].[MUNICIPIO] ([ID]),
    CONSTRAINT [AK_MUNICIPIO_CP] UNIQUE NONCLUSTERED ([ID_CP] ASC, [ID_MUNICIPIO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_MUNICIPIO_CP_ID_CP]
    ON [CALLEJERO].[MUNICIPIO_CP]([ID_CP] ASC);


GO
CREATE NONCLUSTERED INDEX [I_MUNICIPIO_CP_ID_MUNICIPIO]
    ON [CALLEJERO].[MUNICIPIO_CP]([ID_MUNICIPIO] ASC);

