CREATE TABLE [CALLEJERO].[PAIS] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [CODIGO]         VARCHAR (3)   NOT NULL,
    [FECCRE]         DATETIME2 (7) NOT NULL,
    [ID_CREADOR]     INT           NOT NULL,
    [FECMOD]         DATETIME2 (7) NULL,
    [ID_MODIFICADOR] INT           NULL,
    [NOMBRE]         VARCHAR (250) NOT NULL,
    [ISO2]           VARCHAR (2)   DEFAULT ('') NOT NULL,
    [NOMBRE_INGLES]  VARCHAR (250) DEFAULT ('') NOT NULL,
    [PREFIJO]        VARCHAR (10)  DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_PAIS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PAIS_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_PAIS_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [AK_PAIS_CODIGO] UNIQUE NONCLUSTERED ([CODIGO] ASC),
    CONSTRAINT [AK_PAIS_ISO2] UNIQUE NONCLUSTERED ([ISO2] ASC),
    CONSTRAINT [AK_PAIS_NAME] UNIQUE NONCLUSTERED ([NOMBRE_INGLES] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_PAIS_ID_CREADOR]
    ON [CALLEJERO].[PAIS]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PAIS_ID_MODIFICADOR]
    ON [CALLEJERO].[PAIS]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PAIS_NOMBRE]
    ON [CALLEJERO].[PAIS]([NOMBRE] ASC);

