CREATE TABLE [CALLEJERO].[PROVINCIA_CP] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_PROVINCIA] INT NOT NULL,
    [ID_CP]        INT NOT NULL,
    CONSTRAINT [PK_PROVINCIA_CP] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PROVINCIA_CP_ID_CP] FOREIGN KEY ([ID_CP]) REFERENCES [CALLEJERO].[CODIGO_POSTAL] ([ID]),
    CONSTRAINT [FK_PROVINCIA_CP_ID_PROVINCIA] FOREIGN KEY ([ID_PROVINCIA]) REFERENCES [CALLEJERO].[PROVINCIA] ([ID]),
    CONSTRAINT [AK_PROVINCIA_CP_ID_CP] UNIQUE NONCLUSTERED ([ID_CP] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_PROVINCIA_CP_ID_CP]
    ON [CALLEJERO].[PROVINCIA_CP]([ID_CP] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PROVINCIA_CP_ID_PROVINCIA]
    ON [CALLEJERO].[PROVINCIA_CP]([ID_PROVINCIA] ASC);

