CREATE TABLE [CALLEJERO].[PROVINCIA] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [CODIGO]         VARCHAR (2)   NOT NULL,
    [SIGLA]          VARCHAR (3)   NOT NULL,
    [PREFIJO]        VARCHAR (10)  NOT NULL,
    [ID_PAIS]        INT           NOT NULL,
    [NOMBRE]         VARCHAR (250) NOT NULL,
    [FECCRE]         DATETIME2 (7) NOT NULL,
    [ID_CREADOR]     INT           NOT NULL,
    [FECMOD]         DATETIME2 (7) NULL,
    [ID_MODIFICADOR] INT           NULL,
    CONSTRAINT [PK_PROVINCIA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PROVINCIA_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_PROVINCIA_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_PROVINCIA_ID_PAIS] FOREIGN KEY ([ID_PAIS]) REFERENCES [CALLEJERO].[PAIS] ([ID]),
    CONSTRAINT [AK_PROVINCIA_CODIGO] UNIQUE NONCLUSTERED ([CODIGO] ASC),
    CONSTRAINT [AK_PROVINCIA_SIGLA] UNIQUE NONCLUSTERED ([SIGLA] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_PROVINCIA_ID_PAIS]
    ON [CALLEJERO].[PROVINCIA]([ID_PAIS] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PROVINCIA_ID_CREADOR]
    ON [CALLEJERO].[PROVINCIA]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PROVINCIA_ID_MODIFICADOR]
    ON [CALLEJERO].[PROVINCIA]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PROVINCIA_NOMBRE]
    ON [CALLEJERO].[PROVINCIA]([NOMBRE] ASC);

