CREATE TABLE [CALLEJERO].[TIPO_VIA] (
    [ID]     INT           IDENTITY (1, 1) NOT NULL,
    [SIGLA]  VARCHAR (4)   NOT NULL,
    [NOMBRE] VARCHAR (250) NOT NULL,
    CONSTRAINT [PK_TIPO_VIA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [AK_TIPO_VIA_SIGLA] UNIQUE NONCLUSTERED ([SIGLA] ASC)
);


GO
CREATE NONCLUSTERED INDEX [I_TIPO_VIA_NOMBRE]
    ON [CALLEJERO].[TIPO_VIA]([NOMBRE] ASC);

