CREATE TABLE [TERCEROS].[CENTRO_GESTOR_NEGOCIO] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_CG]        INT NOT NULL,
    [ID_NEGOCIO]   INT NOT NULL,
    [ID_CONSULTOR] INT NOT NULL,
    [ID_GESTOR]    INT NOT NULL,
    CONSTRAINT [PK_CENTRO_GESTOR_NEGOCIO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CENTRO_GESTOR_NEGOCIO_ID_CG] FOREIGN KEY ([ID_CG]) REFERENCES [TERCEROS].[CENTRO_GESTOR] ([ID]),
    CONSTRAINT [FK_CENTRO_GESTOR_NEGOCIO_ID_CONSULTOR] FOREIGN KEY ([ID_CONSULTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_CENTRO_GESTOR_NEGOCIO_ID_GESTOR] FOREIGN KEY ([ID_GESTOR]) REFERENCES [SEGURIDAD].[PERMISO] ([ID]),
    CONSTRAINT [FK_CENTRO_GESTOR_NEGOCIO_ID_NEGOCIO] FOREIGN KEY ([ID_NEGOCIO]) REFERENCES [NEGOCIO].[NEGOCIO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_NEGOCIO_ID_CG]
    ON [TERCEROS].[CENTRO_GESTOR_NEGOCIO]([ID_CG] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_NEGOCIO_ID_CONSULTOR]
    ON [TERCEROS].[CENTRO_GESTOR_NEGOCIO]([ID_CONSULTOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_NEGOCIO_ID_GESTOR]
    ON [TERCEROS].[CENTRO_GESTOR_NEGOCIO]([ID_GESTOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_NEGOCIO_ID_NEGOCIO]
    ON [TERCEROS].[CENTRO_GESTOR_NEGOCIO]([ID_NEGOCIO] ASC);

