CREATE TABLE [TERCEROS].[CENTRO_GESTOR] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [ID_SOCIEDAD]    INT           NOT NULL,
    [ID_CG_PADRE]    INT           NULL,
    [CODIGO]         VARCHAR (50)  NOT NULL,
    [EMAIL]          VARCHAR (50)  NOT NULL,
    [ID_RESPONSABLE] INT           NOT NULL,
    [ID_ARCHIVO]     INT           NULL,
    [BAJA]           BIT           DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [NOMBRE]         VARCHAR (250) NOT NULL,
    [FECCRE]         DATETIME2 (7) NOT NULL,
    [ID_CREADOR]     INT           NOT NULL,
    [FECMOD]         DATETIME2 (7) NULL,
    [ID_MODIFICADOR] INT           NULL,
    [SIGLA]          VARCHAR (50)  NULL,
    CONSTRAINT [PK_CENTRO_GESTOR] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_CENTRO_GESTOR_ID_ARCHIVO] FOREIGN KEY ([ID_ARCHIVO]) REFERENCES [SISDOC].[ARCHIVO] ([ID]),
    CONSTRAINT [FK_CENTRO_GESTOR_ID_CG_PADRE] FOREIGN KEY ([ID_CG_PADRE]) REFERENCES [TERCEROS].[CENTRO_GESTOR] ([ID]),
    CONSTRAINT [FK_CENTRO_GESTOR_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_CENTRO_GESTOR_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_CENTRO_GESTOR_ID_RESPONSABLE] FOREIGN KEY ([ID_RESPONSABLE]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_CENTRO_GESTOR_ID_SOCIEDAD] FOREIGN KEY ([ID_SOCIEDAD]) REFERENCES [TERCEROS].[SOCIEDAD] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_ID_CG_PADRE]
    ON [TERCEROS].[CENTRO_GESTOR]([ID_CG_PADRE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_ID_RESPONSABLE]
    ON [TERCEROS].[CENTRO_GESTOR]([ID_RESPONSABLE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_ID_SOCIEDAD]
    ON [TERCEROS].[CENTRO_GESTOR]([ID_SOCIEDAD] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_ID_ARCHIVO]
    ON [TERCEROS].[CENTRO_GESTOR]([ID_ARCHIVO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_ID_CREADOR]
    ON [TERCEROS].[CENTRO_GESTOR]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_ID_MODIFICADOR]
    ON [TERCEROS].[CENTRO_GESTOR]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_CENTRO_GESTOR_NOMBRE]
    ON [TERCEROS].[CENTRO_GESTOR]([NOMBRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_CENTRO_GESTOR_ID_SOCIEDAD_CODIGO]
    ON [TERCEROS].[CENTRO_GESTOR]([ID_SOCIEDAD] ASC, [CODIGO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_CENTRO_GESTOR_ID_SOCIEDAD_NOMBRE]
    ON [TERCEROS].[CENTRO_GESTOR]([ID_SOCIEDAD] ASC, [NOMBRE] ASC);

