CREATE TABLE [TERCEROS].[INTERLOCUTOR] (
    [ID]             INT           IDENTITY (1, 1) NOT NULL,
    [BAJA]           BIT           DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [ID_PERSONA]     INT           NULL,
    [NOMBRE]         VARCHAR (250) NOT NULL,
    [FECCRE]         DATETIME2 (7) NOT NULL,
    [ID_CREADOR]     INT           NOT NULL,
    [FECMOD]         DATETIME2 (7) NULL,
    [ID_MODIFICADOR] INT           NULL,
    [EMAIL]          VARCHAR (50)  DEFAULT ('') NOT NULL,
    [TELEFONO]       VARCHAR (15)  DEFAULT ('') NOT NULL,
    [ID_CONTACTO]    INT           NULL,
    [ID_SOCIEDAD]    INT           NULL,
    CONSTRAINT [PK_INTERLOCUTOR] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_INTERLOCUTOR_ID_CONTACTO] FOREIGN KEY ([ID_CONTACTO]) REFERENCES [TERCEROS].[SOCIEDAD_CONTACTO] ([ID]),
    CONSTRAINT [FK_INTERLOCUTOR_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_INTERLOCUTOR_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_INTERLOCUTOR_ID_PERSONA] FOREIGN KEY ([ID_PERSONA]) REFERENCES [TERCEROS].[PERSONA] ([ID]),
    CONSTRAINT [FK_INTERLOCUTOR_ID_SOCIEDAD] FOREIGN KEY ([ID_SOCIEDAD]) REFERENCES [TERCEROS].[SOCIEDAD] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_INTERLOCUTOR_ID_CREADOR]
    ON [TERCEROS].[INTERLOCUTOR]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_INTERLOCUTOR_ID_MODIFICADOR]
    ON [TERCEROS].[INTERLOCUTOR]([ID_MODIFICADOR] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_INTERLOCUTOR_ID_PERSONA]
    ON [TERCEROS].[INTERLOCUTOR]([ID_PERSONA] ASC) WHERE ([ID_PERSONA] IS NOT NULL);


GO
CREATE UNIQUE NONCLUSTERED INDEX [AK_INTERLOCUTOR]
    ON [TERCEROS].[INTERLOCUTOR]([ID_PERSONA] ASC, [ID_SOCIEDAD] ASC, [ID_CONTACTO] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_INTERLOCUTOR_ID_CONTACTO]
    ON [TERCEROS].[INTERLOCUTOR]([ID_CONTACTO] ASC) WHERE ([ID_CONTACTO] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [I_INTERLOCUTOR_ID_SOCIEDAD]
    ON [TERCEROS].[INTERLOCUTOR]([ID_SOCIEDAD] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_INTERLOCUTOR_NOMBRE]
    ON [TERCEROS].[INTERLOCUTOR]([NOMBRE] ASC);

