CREATE TABLE [TERCEROS].[PERSONA] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [APELLIDOS]       VARCHAR (255) NOT NULL,
    [ES_NIE]          BIT           NOT NULL,
    [NIF]             VARCHAR (15)  NOT NULL,
    [EMAIL]           VARCHAR (50)  NOT NULL,
    [TELEFONO]        VARCHAR (15)  NOT NULL,
    [BAJA]            BIT           DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [NOMBRE]          VARCHAR (250) NOT NULL,
    [FECCRE]          DATETIME2 (7) NOT NULL,
    [ID_CREADOR]      INT           NOT NULL,
    [FECMOD]          DATETIME2 (7) NULL,
    [ID_MODIFICADOR]  INT           NULL,
    [ES_INTERLOCUTOR] AS            ([TERCEROS].[CC_PERSONA_ES_INTERLOCUTOR]([ID])),
    CONSTRAINT [PK_PERSONA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PERSONA_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_PERSONA_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_PERSONA_ID_CREADOR]
    ON [TERCEROS].[PERSONA]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PERSONA_ID_MODIFICADOR]
    ON [TERCEROS].[PERSONA]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_PERSONA_NOMBRE]
    ON [TERCEROS].[PERSONA]([NOMBRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_PERSONA_NIF]
    ON [TERCEROS].[PERSONA]([NIF] ASC);

