CREATE TABLE [TERCEROS].[SOCIEDAD_OBSERVACION] (
    [ID]          INT            IDENTITY (1, 1) NOT NULL,
    [NOMBRE]      VARCHAR (250)  NOT NULL,
    [ID_ELEMENTO] INT            NOT NULL,
    [DESCRIPCION] VARCHAR (2000) NULL,
    [ID_CREADOR]  INT            NOT NULL,
    [CREADO_EL]   DATETIME2 (7)  NOT NULL,
    [ELEMENTO]    AS             ([TERCEROS].[CC_SOCIEDAD_NOMBRE]([ID_ELEMENTO])),
    [CREADOR]     AS             ([ENTORNO].[CC_USUARIO_EXPRESION]([ID_CREADOR])),
    CONSTRAINT [PK_SOCIEDAD_OBSERVACION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SOCIEDAD_OBSERVACION_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_OBSERVACION_ID_ELEMENTO] FOREIGN KEY ([ID_ELEMENTO]) REFERENCES [TERCEROS].[SOCIEDAD] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_OBSERVACION_ID_CREADOR]
    ON [TERCEROS].[SOCIEDAD_OBSERVACION]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_OBSERVACION_ID_ELEMENTO]
    ON [TERCEROS].[SOCIEDAD_OBSERVACION]([ID_ELEMENTO] ASC);

