CREATE TABLE [TERCEROS].[SOCIEDAD] (
    [ID]              INT           IDENTITY (1, 1) NOT NULL,
    [RAZON_SOCIAL]    VARCHAR (255) NOT NULL,
    [CODIGO_FISCAL]   VARCHAR (4)   NULL,
    [CODIGO_CONTABLE] VARCHAR (4)   NULL,
    [NIF]             VARCHAR (15)  NOT NULL,
    [EMAIL]           VARCHAR (50)  NOT NULL,
    [TELEFONO]        VARCHAR (15)  NOT NULL,
    [BAJA]            BIT           DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [NOMBRE]          VARCHAR (250) NOT NULL,
    [FECCRE]          DATETIME2 (7) NOT NULL,
    [ID_CREADOR]      INT           NOT NULL,
    [FECMOD]          DATETIME2 (7) NULL,
    [ID_MODIFICADOR]  INT           NULL,
    [ES_INTERLOCUTOR] AS            ([TERCEROS].[CC_SOCIEDAD_ES_INTERLOCUTOR]([ID])),
    CONSTRAINT [PK_SOCIEDAD] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SOCIEDAD_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_ID_MODIFICADOR] FOREIGN KEY ([ID_MODIFICADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_ID_CREADOR]
    ON [TERCEROS].[SOCIEDAD]([ID_CREADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_ID_MODIFICADOR]
    ON [TERCEROS].[SOCIEDAD]([ID_MODIFICADOR] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_NOMBRE]
    ON [TERCEROS].[SOCIEDAD]([NOMBRE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_SOCIEDAD_NIF]
    ON [TERCEROS].[SOCIEDAD]([NIF] ASC);

