CREATE TABLE [TERCEROS].[SOCIEDAD_ARCHIVO] (
    [ID]           INT IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO1] INT NOT NULL,
    [ID_ELEMENTO2] INT NOT NULL,
    CONSTRAINT [PK_SOCIEDAD_ARCHIVO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SOCIEDAD_ARCHIVO_ID_ELEMENTO1] FOREIGN KEY ([ID_ELEMENTO1]) REFERENCES [TERCEROS].[SOCIEDAD] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_ARCHIVO_ID_ELEMENTO2] FOREIGN KEY ([ID_ELEMENTO2]) REFERENCES [SISDOC].[ARCHIVO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_ARCHIVO_ID_ELEMENTO1]
    ON [TERCEROS].[SOCIEDAD_ARCHIVO]([ID_ELEMENTO1] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_ARCHIVO_ID_ELEMENTO2]
    ON [TERCEROS].[SOCIEDAD_ARCHIVO]([ID_ELEMENTO2] ASC);

