CREATE TABLE [TERCEROS].[SOCIEDAD_CONTACTO] (
    [ID]              INT            IDENTITY (1, 1) NOT NULL,
    [ID_SOCIEDAD]     INT            NOT NULL,
    [EMAIL]           VARCHAR (50)   NOT NULL,
    [TELEFONO]        VARCHAR (15)   NOT NULL,
    [BAJA]            BIT            DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [DESCRIPCION]     VARCHAR (2000) NULL,
    [NOMBRE]          VARCHAR (250)  NOT NULL,
    [ES_INTERLOCUTOR] AS             ([TERCEROS].[CC_SOCIEDAD_CONTACTO_ES_INTERLOCUTOR]([ID])),
    CONSTRAINT [PK_SOCIEDAD_CONTACTO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SOCIEDAD_CONTACTO_ID_SOCIEDAD] FOREIGN KEY ([ID_SOCIEDAD]) REFERENCES [TERCEROS].[SOCIEDAD] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_CONTACTO_ID_SOCIEDAD]
    ON [TERCEROS].[SOCIEDAD_CONTACTO]([ID_SOCIEDAD] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [I_SOCIEDAD_CONTACTO_ID_SOCIEDAD_NOMBRE]
    ON [TERCEROS].[SOCIEDAD_CONTACTO]([ID_SOCIEDAD] ASC, [NOMBRE] ASC);

