CREATE TABLE [TERCEROS].[SOCIEDAD_DIRECCION] (
    [ID]           INT            IDENTITY (1, 1) NOT NULL,
    [ID_ELEMENTO]  INT            NOT NULL,
    [CALIFICADOR]  VARCHAR (20)   NOT NULL,
    [ID_PAIS]      INT            NOT NULL,
    [ID_PROVINCIA] INT            NOT NULL,
    [ID_MUNICIPIO] INT            NOT NULL,
    [ID_CALLE]     INT            NOT NULL,
    [ID_ZONA]      INT            NULL,
    [ID_BARRIO]    INT            NULL,
    [ID_CP]        INT            NULL,
    [NUMERO]       INT            NULL,
    [ESCALERA]     VARCHAR (4)    NULL,
    [PISO]         VARCHAR (4)    NULL,
    [PUERTA]       VARCHAR (15)   NULL,
    [OTROS]        VARCHAR (2000) NULL,
    [URL]          VARCHAR (2000) NULL,
    [ACTIVO]       BIT            NOT NULL,
    [CREADO_EL]    DATETIME2 (7)  DEFAULT ('0001-01-01T00:00:00.0000000') NOT NULL,
    [ID_CREADOR]   INT            DEFAULT ((0)) NOT NULL,
    [CREADOR]      AS             ([ENTORNO].[CC_USUARIO_EXPRESION]([ID_CREADOR])),
    CONSTRAINT [PK_SOCIEDAD_DIRECCION] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SOCIEDAD_DIRECCION_ID_BARRIO] FOREIGN KEY ([ID_BARRIO]) REFERENCES [CALLEJERO].[BARRIO] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_DIRECCION_ID_CALLE] FOREIGN KEY ([ID_CALLE]) REFERENCES [CALLEJERO].[CALLE] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_DIRECCION_ID_CP] FOREIGN KEY ([ID_CP]) REFERENCES [CALLEJERO].[CODIGO_POSTAL] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_DIRECCION_ID_CREADOR] FOREIGN KEY ([ID_CREADOR]) REFERENCES [ENTORNO].[USUARIO] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_DIRECCION_ID_ELEMENTO] FOREIGN KEY ([ID_ELEMENTO]) REFERENCES [TERCEROS].[SOCIEDAD] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_DIRECCION_ID_MUNICIPIO] FOREIGN KEY ([ID_MUNICIPIO]) REFERENCES [CALLEJERO].[MUNICIPIO] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_DIRECCION_ID_PAIS] FOREIGN KEY ([ID_PAIS]) REFERENCES [CALLEJERO].[PAIS] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_DIRECCION_ID_PROVINCIA] FOREIGN KEY ([ID_PROVINCIA]) REFERENCES [CALLEJERO].[PROVINCIA] ([ID]),
    CONSTRAINT [FK_SOCIEDAD_DIRECCION_ID_ZONA] FOREIGN KEY ([ID_ZONA]) REFERENCES [CALLEJERO].[ZONA] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [AK_SOCIEDAD_DIRECCION]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([CALIFICADOR] ASC, [ID_ELEMENTO] ASC, [ID_PAIS] ASC, [ID_PROVINCIA] ASC, [ID_MUNICIPIO] ASC, [ID_CALLE] ASC, [NUMERO] ASC, [PUERTA] ASC, [ESCALERA] ASC, [PISO] ASC) WHERE ([NUMERO] IS NOT NULL AND [PUERTA] IS NOT NULL AND [ESCALERA] IS NOT NULL AND [PISO] IS NOT NULL);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_DIRECCION_ID_BARRIO]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([ID_BARRIO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_DIRECCION_ID_CALLE]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([ID_CALLE] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_DIRECCION_ID_CP]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([ID_CP] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_DIRECCION_ID_ELEMENTO]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([ID_ELEMENTO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_DIRECCION_ID_MUNICIPIO]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([ID_MUNICIPIO] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_DIRECCION_ID_PAIS]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([ID_PAIS] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_DIRECCION_ID_PROVINCIA]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([ID_PROVINCIA] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_DIRECCION_ID_ZONA]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([ID_ZONA] ASC);


GO
CREATE NONCLUSTERED INDEX [I_SOCIEDAD_DIRECCION_ID_CREADOR]
    ON [TERCEROS].[SOCIEDAD_DIRECCION]([ID_CREADOR] ASC);

