//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnet.Login
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://solicitudlogintoken.servicio.wslexnet.webservices.lexnet", ConfigurationName="Lexnet.Login.SolicitudLoginTokenPortType")]
    public interface SolicitudLoginTokenPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Lexnet.Login.SolicitudLoginTokenResponse> SolicitudLoginTokenAsync(Lexnet.Login.SolicitudLoginTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitudLoginTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://solicitudlogintoken.servicio.wslexnet.webservices.lexnet", Order=0)]
        public string SolicitudLoginTokenIn;
        
        public SolicitudLoginTokenRequest()
        {
        }
        
        public SolicitudLoginTokenRequest(string SolicitudLoginTokenIn)
        {
            this.SolicitudLoginTokenIn = SolicitudLoginTokenIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SolicitudLoginTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://solicitudlogintoken.servicio.wslexnet.webservices.lexnet", Order=0)]
        public string SolicitudLoginTokenOut;
        
        public SolicitudLoginTokenResponse()
        {
        }
        
        public SolicitudLoginTokenResponse(string SolicitudLoginTokenOut)
        {
            this.SolicitudLoginTokenOut = SolicitudLoginTokenOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface SolicitudLoginTokenPortTypeChannel : Lexnet.Login.SolicitudLoginTokenPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SolicitudLoginTokenPortTypeClient : System.ServiceModel.ClientBase<Lexnet.Login.SolicitudLoginTokenPortType>, Lexnet.Login.SolicitudLoginTokenPortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SolicitudLoginTokenPortTypeClient() : 
                base(SolicitudLoginTokenPortTypeClient.GetDefaultBinding(), SolicitudLoginTokenPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SolicitudLoginToken.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolicitudLoginTokenPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(SolicitudLoginTokenPortTypeClient.GetBindingForEndpoint(endpointConfiguration), SolicitudLoginTokenPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolicitudLoginTokenPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SolicitudLoginTokenPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolicitudLoginTokenPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SolicitudLoginTokenPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SolicitudLoginTokenPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lexnet.Login.SolicitudLoginTokenResponse> Lexnet.Login.SolicitudLoginTokenPortType.SolicitudLoginTokenAsync(Lexnet.Login.SolicitudLoginTokenRequest request)
        {
            return base.Channel.SolicitudLoginTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lexnet.Login.SolicitudLoginTokenResponse> SolicitudLoginTokenAsync(string SolicitudLoginTokenIn)
        {
            Lexnet.Login.SolicitudLoginTokenRequest inValue = new Lexnet.Login.SolicitudLoginTokenRequest();
            inValue.SolicitudLoginTokenIn = SolicitudLoginTokenIn;
            return ((Lexnet.Login.SolicitudLoginTokenPortType)(this)).SolicitudLoginTokenAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SolicitudLoginToken))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SolicitudLoginToken))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:9080/lexnetWeb/services/SolicitudLoginToken");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SolicitudLoginTokenPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.SolicitudLoginToken);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SolicitudLoginTokenPortTypeClient.GetEndpointAddress(EndpointConfiguration.SolicitudLoginToken);
        }
        
        public enum EndpointConfiguration
        {
            
            SolicitudLoginToken,
        }
    }
}
